sw360/sw360portal

- libraries/lib-datahandler/pom.xml
- libraries/lib-datahandler/src/test/java/com/siemens/sw360/datahandler/permissions/ProjectPermissionsVisibilityTest.java
- libraries/lib-datahandler/src/test/java/com/siemens/sw360/datahandler/permissions/jgivens/GivenProjectsWithVisibility.java
- pom.xml
This simplifies adding new test scenarios and increases the readability of the tests and the test output.
> Refactored some jgiven tests to use dataprovider

- libraries/exporters/src/main/java/com/siemens/sw360/exporter/ComponentExporter.java
changed header of excel export such that it does not contain CPE-ID any more
> fixed error when exporting Components

- frontend/sw360-portlets/src/main/java/com/siemens/sw360/portal/portlets/admin/VendorPortlet.java
- frontend/sw360-portlets/src/main/webapp/html/admin/vendors/edit.jsp
- frontend/sw360-portlets/src/main/webapp/html/projects/edit.jsp
- libraries/lib-datahandler/src/main/java/com/siemens/sw360/datahandler/couchdb/lucene/LuceneAwareDatabaseConnector.java
- pom.xml
> facilitate adding a vendor in vendorPortlet

- backend/src-common/src/main/java/com/siemens/sw360/datahandler/db/ProjectDatabaseHandler.java
- frontend/sw360-portlets/src/main/java/com/siemens/sw360/portal/portlets/projects/ProjectPortlet.java
- frontend/sw360-portlets/src/main/java/com/siemens/sw360/portal/tags/links/DisplayLinkAbstract.java
- frontend/sw360-portlets/src/main/java/com/siemens/sw360/portal/tags/links/DisplayLinkToProject.java
- frontend/sw360-portlets/src/main/webapp/WEB-INF/customTags.tld
- frontend/sw360-portlets/src/main/webapp/html/projects/ajax/linkedProjectsAjax.jsp
- frontend/sw360-portlets/src/main/webapp/html/projects/includes/linkedProjects.jspf
- libraries/lib-datahandler/src/main/thrift/projects.thrift
Added project link version, and made project name clickable as redirekt to linkee
> Added project link version

- backend/src-common/src/main/java/com/siemens/sw360/components/summary/ComponentSummary.java
- backend/src-common/src/main/java/com/siemens/sw360/datahandler/db/ComponentSearchHandler.java
- frontend/pom.xml
- frontend/sw360-portlets/src/main/java/com/siemens/sw360/portal/common/PortalConstants.java
- frontend/sw360-portlets/src/main/java/com/siemens/sw360/portal/portlets/components/ComponentPortlet.java
- frontend/sw360-portlets/src/main/java/com/siemens/sw360/portal/tags/DisplayEnumSelection.java
- frontend/sw360-portlets/src/main/java/com/siemens/sw360/portal/tags/OutTag.java
- frontend/sw360-portlets/src/main/webapp/WEB-INF/customTags.tld
- frontend/sw360-portlets/src/main/webapp/html/components/includes/components/summary.jspf
- frontend/sw360-portlets/src/main/webapp/html/components/view.jsp
Add type to Component filter
Add Type to Component view and detail view
closes #13
> Make type visible for component

- frontend/sw360-portlets/src/main/java/com/siemens/sw360/portal/common/PortletUtils.java
- frontend/sw360-portlets/src/main/webapp/html/projects/includes/projects/usingProjects.jspf
- frontend/sw360-portlets/src/main/webapp/html/utils/ajax/attachmentsAjax.jsp
- frontend/sw360-portlets/src/main/webapp/html/utils/includes/attachmentsDelete.jsp
- frontend/sw360-portlets/src/main/webapp/html/utils/includes/attachmentsDetail.jsp
- frontend/sw360-portlets/src/main/webapp/html/utils/includes/attachmentsUpload.jsp
- frontend/sw360-portlets/src/main/webapp/html/utils/includes/editAttachments.jsp
- libraries/lib-datahandler/src/main/java/com/siemens/sw360/datahandler/common/CommonUtils.java
- libraries/lib-datahandler/src/main/java/com/siemens/sw360/datahandler/common/ThriftEnumUtils.java
fix delete attachments
closes #3
> added approvers to attachments

- frontend/sw360-portlets/src/main/webapp/html/admin/vendors/edit.jsp
- frontend/sw360-portlets/src/main/webapp/html/components/editRelease.jsp
- frontend/sw360-portlets/src/main/webapp/html/components/includes/vendors/addVendorForm.jspf
former pull request was accidentally closed 
this is the same as before
> Fix vendor required fields

- backend/src-common/src/main/java/com/siemens/sw360/components/summary/ComponentSummary.java
- backend/src-common/src/main/java/com/siemens/sw360/components/summary/SummaryType.java
- backend/src-common/src/main/java/com/siemens/sw360/datahandler/db/ComponentDatabaseHandler.java
- backend/src-common/src/main/java/com/siemens/sw360/datahandler/db/ReleaseRepository.java
- backend/src-common/src/main/java/com/siemens/sw360/projects/Sw360ThriftServlet.java
- backend/src/src-attachments/src/main/java/com/siemens/sw360/attachments/AttachmentServlet.java
- backend/src/src-components/src/main/java/com/siemens/sw360/components/ComponentServlet.java
- backend/src/src-fossology/src/main/java/com/siemens/sw360/fossology/SpringTServlet.java
- backend/src/src-licenses/src/main/java/com/siemens/sw360/licenses/LicenseServlet.java
- backend/src/src-moderation/src/main/java/com/siemens/sw360/moderation/ModerationServlet.java
- backend/src/src-projects/src/main/java/com/siemens/sw360/projects/ProjectServlet.java
- backend/src/src-search/src/main/java/com/siemens/sw360/search/SearchServlet.java
- backend/src/src-users/src/main/java/com/siemens/sw360/users/UserServlet.java
- backend/src/src-vendors/src/main/java/com/siemens/sw360/vendors/VendorServlet.java
- frontend/sw360-portlets/src/main/java/com/siemens/sw360/portal/portlets/homepage/MyComponentsPortlet.java
- frontend/sw360-portlets/src/main/webapp/html/homepage/mycomponents/view.jsp
> fix MyComponents and add Sw360Servlet class

- frontend/sw360-portlets/src/main/java/com/siemens/sw360/portal/portlets/PortletProperties.java
> Hotfixes broken links to License details view for 110SNAPSHOT

- pom.xml
This adds the plugins mentioned in https://github.com/siemens/sw360portal/wiki/Dev-releasing-SW360
They will wrap the process of releasing and tagging.
> feature(pom.xml): add plugins for tagging and setting versions

- backend/src-common/src/main/java/com/siemens/sw360/components/summary/DocumentSummary.java
- backend/src-common/src/main/java/com/siemens/sw360/components/summary/LicenseTypeSummary.java
- backend/src/src-licenses/src/main/java/com/siemens/sw360/licenses/LicenseHandler.java
- backend/src/src-licenses/src/main/java/com/siemens/sw360/licenses/db/LicenseDatabaseHandler.java
- backend/src/src-licenses/src/main/java/com/siemens/sw360/licenses/db/LicenseTypeRepository.java
- frontend/sw360-portlet/src/main/java/com/siemens/sw360/portal/portlets/licenses/LicensesPortlet.java
- libraries/exporters/src/main/java/com/siemens/sw360/exporter/LicenseExporter.java
- libraries/lib-datahandler/src/main/thrift/licenses.thrift
> licenseExporter enriched with licenseType

- backend/pom.xml
> Add missing fields back to `backend/pom.xml`

- backend/src-common/src/main/java/com/siemens/sw360/components/summary/ProjectSummary.java
- frontend/sw360-portlet/src/main/java/com/siemens/sw360/portal/portlets/projects/ProjectPortlet.java
- frontend/sw360-portlet/src/main/webapp/html/components/includes/releases/clearingDetails.jspf
- frontend/sw360-portlet/src/main/webapp/html/homepage/welcome/view.jsp
field is computed correctly
closes #95
> fixed ReleaseClearingStateSummary in Project Standard View:

- frontend/sw360-portlet/src/main/java/com/siemens/sw360/portal/portlets/admin/VendorPortlet.java
- frontend/sw360-portlet/src/main/webapp/html/admin/bulkReleaseEdit/view.jsp
- frontend/sw360-portlet/src/main/webapp/html/admin/vendors/edit.jsp
- frontend/sw360-portlet/src/main/webapp/html/admin/vendors/view.jsp
- frontend/sw360-portlet/src/main/webapp/html/components/ajax/vendorAjax.jsp
- frontend/sw360-portlet/src/main/webapp/html/components/ajax/vendorSearch.jsp
- frontend/sw360-portlet/src/main/webapp/html/components/editRelease.jsp
- frontend/sw360-portlet/src/main/webapp/html/components/includes/vendors/addVendorForm.jspf
- frontend/sw360-portlet/src/main/webapp/html/components/includes/vendors/vendorDetail.jspf
- frontend/sw360-portlet/src/main/webapp/html/components/includes/vendors/vendorSearchForm.jspf
- add button always present in releases-set vendor
- vendor list in releases-set vendor with consistent names
- Vendors throughout SW360 always in order Full Name, Short Name, URL
- Delete Function in vendor/edit.jsp
- fixed broken vendor table in vendor/view.jsp (links to edit-pages were broken)
- closes #73
- closes #124
> Improve vendor handling:

- frontend/sw360-portlet/src/main/java/com/siemens/sw360/portal/portlets/components/ComponentPortlet.java
- frontend/sw360-portlet/src/main/java/com/siemens/sw360/portal/portlets/projects/ProjectPortlet.java
After adding a new project/component, stay in edit mode of that project/component (in order to upload attachments and proceed editing).
After updating an existing project/component, go to detail view of that project/component.
This is the same as it already was for releases.
> closes #130

- frontend/sw360-portlet/src/main/webapp/html/components/includes/releases/editReleaseInformation.jspf
> made Release field Programming Languages optional

- frontend/sw360-portlet/src/main/webapp/html/components/includes/components/editBasicInfo.jspf
- frontend/sw360-portlet/src/main/webapp/html/components/includes/releases/summaryRelease.jspf
- frontend/sw360-portlet/src/main/webapp/html/projects/includes/projects/summary.jspf
- added missing fields to summary display:
* Project.state
* Release.languages
* Release.operatingSystems
- corrected a couple typos
closes #160
> added missing fields to summary display, fixed some typos

- frontend/sw360-portlet/src/main/java/com/siemens/sw360/portal/tags/DisplayDescription.java
- frontend/sw360-portlet/src/main/java/com/siemens/sw360/portal/tags/OutTag.java
- frontend/sw360-portlet/src/main/webapp/WEB-INF/customTags.tld
- frontend/sw360-portlet/src/main/webapp/html/projects/includes/projects/basicInfo.jspf
* fixed display and editing of a multiline project description
* moved DisplayDescription to the correct package folder
* fixed abbreviation in OutTag
closes #152
> fixed display and editing of a multiline project description

- backend/src-common/src/main/java/com/siemens/sw360/datahandler/db/ComponentDatabaseHandler.java
- backend/src/src-components/src/main/java/com/siemens/sw360/components/ComponentHandler.java
- frontend/sw360-portlet/src/main/java/com/siemens/sw360/portal/portlets/components/ComponentPortletUtils.java
- libraries/lib-datahandler/src/main/java/com/siemens/sw360/datahandler/common/CommonUtils.java
- libraries/lib-datahandler/src/main/thrift/components.thrift
* fixed autosetting release clearing state on clearing report removal
* also fixed the case when a clearing report gets quasi-removed by changing its attachment type
* removed methods removeAttachmentFromComponent and removeAttachmentFromRelease from Component service
closes #157
> fixed autosetting release clearing state on clearing report removal

- frontend/sw360-portlet/src/main/java/com/siemens/sw360/portal/common/PortalConstants.java
- frontend/sw360-portlet/src/main/java/com/siemens/sw360/portal/portlets/projects/ProjectPortlet.java
- frontend/sw360-portlet/src/main/java/com/siemens/sw360/portal/portlets/projects/ProjectPortletUtils.java
- frontend/sw360-portlet/src/main/webapp/html/homepage/welcome/view.jsp
- frontend/sw360-portlet/src/main/webapp/html/projects/includes/projects/basicInfo.jspf
- frontend/sw360-portlet/src/main/webapp/html/projects/includes/projects/summary.jspf
- frontend/sw360-portlet/src/main/webapp/html/projects/view.jsp
- libraries/exporters/src/main/java/com/siemens/sw360/exporter/ProjectExporter.java
- libraries/lib-datahandler/src/main/java/com/siemens/sw360/datahandler/common/ThriftEnumUtils.java
also renamed Business Unit to Group in the UI
closes #147
> added sticky (saved between sessions) project filter by group

- libraries/lib-datahandler/src/main/java/com/siemens/sw360/datahandler/common/CommonUtils.java
the files placed at /etc/sw360/ overwrite the values in the other property files
> allow property files to be placed at `/etc/sw360/`

- frontend/sw360-portlet/src/main/webapp/html/projects/detail.jsp
- frontend/sw360-portlet/src/main/webapp/html/projects/includes/linkedProjects.jspf
- frontend/sw360-portlet/src/main/webapp/html/utils/includes/linkedReleaseDetails.jspf
Renamed tables and tabs to better reflect current state.
> added directly linked releases of the project to linkedProjects

- frontend/sw360-portlet/src/main/webapp/html/components/includes/releases/editReleaseInformation.jspf
...and correct formula for CPE ID generation in the tooltip
> make CPE ID editable

- backend/src/src-fossology/src/main/java/com/siemens/sw360/fossology/handler/FossologyFileHandler.java
- backend/src/src-fossology/src/test/java/com/siemens/sw360/fossology/handler/FossologyFileHandlerTest.java
- frontend/sw360-portlet/src/main/java/com/siemens/sw360/portal/portlets/components/ComponentPortlet.java
- frontend/sw360-portlet/src/main/java/com/siemens/sw360/portal/portlets/components/ComponentPortletUtils.java
- frontend/sw360-portlet/src/main/webapp/html/components/includes/releases/editReleaseInformation.jspf
- libraries/lib-datahandler/src/main/java/com/siemens/sw360/datahandler/businessrules/ReleaseClearingStateSummaryComputer.java
- libraries/lib-datahandler/src/test/java/com/siemens/sw360/datahandler/businessrules/ReleaseClearingStateSummaryComputerTest.java
- libraries/lib-datahandler/src/test/java/com/siemens/sw360/datahandler/businessrules/jgivens/ThenReleaseClearingState.java
completed automatic management of release clearing state and removed the option of setting it manually.
closes #127
> Autosetting clearing state#127

- frontend/sw360-portlet/src/main/java/com/siemens/sw360/portal/portlets/projects/ProjectPortlet.java
> Set default project visibility to "groups and moderators"

- frontend/sw360-portlet/src/main/webapp/html/components/includes/releases/editReleaseClearingInformation.jspf
- frontend/sw360-portlet/src/main/webapp/html/components/includes/releases/editReleaseInformation.jspf
- frontend/sw360-portlet/src/main/webapp/html/projects/includes/projects/basicInfo.jspf
> Added datapicker for Release Date, Evaluation Date and Process Start

- backend/src/src-moderation/src/main/java/com/siemens/sw360/moderation/db/COTSDetailsModerationRequestGenerator.java
- backend/src/src-moderation/src/main/java/com/siemens/sw360/moderation/db/ClearingInformationModerationRequestGenerator.java
- frontend/sw360-portlet/src/main/java/com/siemens/sw360/portal/tags/DisplayProjectChanges.java
- frontend/sw360-portlet/src/main/java/com/siemens/sw360/portal/tags/DisplayReleaseChanges.java
- frontend/sw360-portlet/src/main/webapp/html/moderation/projects/merge.jsp
- libraries/lib-datahandler/src/main/java/com/siemens/sw360/datahandler/common/CommonUtils.java
- libraries/lib-datahandler/src/main/java/com/siemens/sw360/datahandler/common/Moderator.java
* added missing import in projects/merge.jsp
* Projects, releases, components imported from a datasource outside SW360 have several fields not set/null that are usually initialized when
generating the document in the SW360-UI. This caused NullPointerExceptions. This problem is fixed now.
> fixed NullPointerExceptions in Moderation Requests

- README.md
Also wrote that the users are encouraged to report issues.
Now from the patch branch.
> Make the problem text a little bit more clearer.

- backend/src/src-licenseinfo/src/main/java/com/siemens/sw360/licenseinfo/parsers/CLIParser.java
- backend/src/src-licenseinfo/src/main/java/com/siemens/sw360/licenseinfo/parsers/SPDXParser.java
- backend/utils/src/main/java/com/siemens/sw360/attachments/db/RemoteAttachmentDownloader.java
- libraries/lib-datahandler/src/main/java/com/siemens/sw360/datahandler/common/CommonUtils.java
- libraries/lib-datahandler/src/main/java/com/siemens/sw360/datahandler/couchdb/AttachmentConnector.java
- libraries/lib-datahandler/src/main/java/com/siemens/sw360/datahandler/couchdb/AttachmentStreamConnector.java
> ensured consistent closing of attachment InputStream

- .gitignore
- frontend/sw360-portlet/src/main/java/com/siemens/sw360/portal/tags/DisplayReleaseClearingStateSummary.java
- ignoring *.log in .gitignore (prompted by velocity.log file)
- fixed a NullPointerException in DisplayReleaseClearingStateSummary
> minor housekeeping improvements

- backend/src-common/src/main/java/com/siemens/sw360/datahandler/db/ComponentDatabaseHandler.java
- frontend/sw360-portlet/src/main/webapp/html/utils/includes/linkedReleaseDetails.jspf
- libraries/lib-datahandler/src/main/thrift/components.thrift
> add clearing state to release details - linked releases page

- frontend/sw360-portlet/src/main/webapp/html/projects/edit.jsp
* probably that was a rebase problem of the previous PR
> add and cancel button in projects-edit were displayed twice - fixed

- frontend/sw360-portlet/src/main/java/com/siemens/sw360/portal/portlets/components/ComponentPortlet.java
- frontend/sw360-portlet/src/main/java/com/siemens/sw360/portal/portlets/projects/ProjectPortlet.java
- frontend/sw360-portlet/src/main/webapp/html/projects/includes/linkedProjects.jspf
- frontend/sw360-portlet/src/main/webapp/html/utils/includes/linkedReleaseDetails.jspf
- libraries/lib-datahandler/src/main/java/com/siemens/sw360/datahandler/common/ThriftEnumUtils.java
- Changed display strings of project and release relationships CONTAINED and REFERRED to more self-explaining 'Is a subproject' (resp. 'Is a subrelease') and 'Related'.
- Changed default relationship from UNKNOWN to REFERRED
closes #210
> Improved links to projects and releases

- frontend/sw360-portlet/src/main/webapp/css/main.css
- frontend/sw360-portlet/src/main/webapp/html/components/includes/releases/summaryRelease.jspf
- frontend/sw360-theme/src/main/webapp/templates/navigation.vm
* css styling of navigation bar: remove borders: closes #239
* display externalIds for releases: partly closes issue 254, but let's keep the issue open until it is clear whether this is enough already
> navigation bar styling and externalIds display release details

- frontend/sw360-portlet/src/main/webapp/html/components/includes/releases/clearingDetails.jspf
- frontend/sw360-portlet/src/main/webapp/html/components/includes/releases/editReleaseClearingInformation.jspf
- frontend/sw360-portlet/src/main/webapp/html/components/includes/releases/summaryRelease.jspf
- renamed fields in release detail view
- rearranged fields of release clearing details in display and edit mode
closes #189 
closes #191
> rename labels in release detail view

- frontend/sw360-portlet/src/main/webapp/html/projects/view.jsp
> fixed escaping projects' description for javascript

- frontend/sw360-portlet/src/main/webapp/html/admin/bulkReleaseEdit/view.jsp
- frontend/sw360-portlet/src/main/webapp/html/admin/vendors/view.jsp
- frontend/sw360-portlet/src/main/webapp/html/components/includes/components/clearingStatus.jspf
- frontend/sw360-portlet/src/main/webapp/html/components/includes/components/vulnerabilities.jspf
- frontend/sw360-portlet/src/main/webapp/html/components/includes/releases/vulnerabilities.jspf
- frontend/sw360-portlet/src/main/webapp/html/components/view.jsp
- frontend/sw360-portlet/src/main/webapp/html/homepage/mytasksubmissions/view.jsp
- frontend/sw360-portlet/src/main/webapp/html/licenses/view.jsp
- frontend/sw360-portlet/src/main/webapp/html/moderation/view.jsp
- frontend/sw360-portlet/src/main/webapp/html/projects/import.jsp
- frontend/sw360-portlet/src/main/webapp/html/projects/includes/projects/clearingStatus.jspf
- frontend/sw360-portlet/src/main/webapp/html/projects/includes/projects/vulnerabilities.jspf
- frontend/sw360-portlet/src/main/webapp/html/projects/view.jsp
- frontend/sw360-portlet/src/main/webapp/html/vulnerabilities/view.jsp
- frontend/sw360-portlet/src/main/webapp/js/licenses.js
renamed all oTable JS vars to specific names to fix #268 and prevent similar potential problems. closes #268, closes #232
fixed resetting to the first page after rows are deleted from datatables. closes #271
> Fixed Problems With Datatables Handling

- frontend/sw360-portlet/src/main/webapp/html/components/includes/components/editBasicInfo.jspf
- frontend/sw360-portlet/src/main/webapp/html/components/includes/components/summary.jspf
- frontend/sw360-portlet/src/main/webapp/html/components/includes/releases/clearingDetails.jspf
- frontend/sw360-portlet/src/main/webapp/html/components/includes/releases/editReleaseClearingInformation.jspf
- frontend/sw360-portlet/src/main/webapp/html/components/includes/releases/summaryRelease.jspf
- frontend/sw360-portlet/src/main/webapp/html/projects/includes/projects/basicInfo.jspf
* most links were already displayed properly
* added link-display for release dowloadUrl, ClearingInfo externalUrl and repositoryUrl of releases
* input of all url-fields in edit mode changed to type="URL" (checks validity of url, but does not insist when the user safes document)
* added mailto to mailing list of component
> improved display of external links

- backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/LicenseInfoHandler.java
- backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxGenerator.java
- backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxUtils.java
- backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/LicenseInfoGenerator.java
- backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/XhtmlGenerator.java
- backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/parsers/CLIParser.java
- backend/src/src-licenseinfo/src/main/resources/licenseInfoFile.vm
- backend/src/src-licenseinfo/src/main/resources/xhtmlFile.vm
- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/CommonUtils.java
- libraries/lib-datahandler/src/main/thrift/licenseinfo.thrift
- added reading acknowledgements from CLI files for license info generation
- also added reading license names from CLI files (for xhtml output)
> Acknowledgements from CLI in License Info

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
> correctly load using components and projects for component editing

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
- backend/src/src-components/src/test/java/org/eclipse/sw360/components/db/ProjectDatabaseHandlerTest.java
- frontend/sw360-portlet/src/main/webapp/html/projects/licenseInfo.jsp
- libraries/lib-datahandler/src/main/thrift/projects.thrift
Added column for showing tree level of releases and projects at licenseInfo generation
Closes #305
> Show Hierarchy Level at LicenseInfo Generation Page

- backend/src-common/src/main/java/org/eclipse/sw360/mail/MailUtil.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/DisplayProjectChanges.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/DisplayUserEdit.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/DisplayUserEmail.java
- if user is stored in a field of a document, display user's email in details and edit view
- this way, in edit mode, the user is not deleted silently
> display non-existing user with email

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/AttachmentPortletUtils.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/TagUtils.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/links/DisplayDownloadAttachment.java
- frontend/sw360-portlet/src/main/webapp/WEB-INF/customTags.tld
- frontend/sw360-portlet/src/main/webapp/html/projects/includes/attachmentSelectTable.jspf
- frontend/sw360-portlet/src/main/webapp/html/projects/includes/linkedProjects.jspf
- frontend/sw360-portlet/src/main/webapp/html/projects/sourceCodeBundle.jsp
- frontend/sw360-portlet/src/main/webapp/html/utils/includes/attachmentsDetail.jsp
- frontend/sw360-portlet/src/test/java/org/eclipse/sw360/portal/tags/links/DisplayDownloadAttachmentTest.java
- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Constants.java
- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/AttachmentStreamConnector.java
This PR contains a feature that allows to download a source code bundle for a project similar to the generation of the notice file.
> Download Source Code Bundle for a Project

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
- backend/src/src-projects/src/main/java/org/eclipse/sw360/projects/ProjectHandler.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
- frontend/sw360-portlet/src/main/webapp/html/components/view.jsp
- frontend/sw360-portlet/src/main/webapp/html/projects/includes/linkedProjects.jspf
- frontend/sw360-portlet/src/main/webapp/html/projects/view.jsp
- libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ProjectExporter.java
- libraries/lib-datahandler/src/main/thrift/projects.thrift
- added the possibility to download project export for a single project and its subprojects from the "Linked Releases And Projects" tab.
- also renamed Export Excel to Export Spreadsheet
closes #325
> WIP: Added Spreadsheet Export For Specific Products

- backend/src-common/src/test/java/org/eclipse/sw360/components/summary/ProjectSummaryTest.java
- frontend/sw360-portlet/src/main/webapp/html/projects/includes/projects/basicInfo.jspf
- frontend/sw360-portlet/src/main/webapp/html/projects/includes/projects/summary.jspf
- libraries/lib-datahandler/src/main/thrift/projects.thrift
Added field "Security Responsibles" to projects
> Added Security Responsibles To Projects

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/LinkToPortletConfiguration.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/moderation/ModerationPortlet.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/links/DisplayLinkToModerationRequest.java
- frontend/sw360-portlet/src/main/webapp/WEB-INF/customTags.tld
- frontend/sw360-portlet/src/main/webapp/html/homepage/mytaskassignments/view.jsp
- frontend/sw360-portlet/src/main/webapp/html/homepage/mytasksubmissions/view.jsp
- frontend/sw360-portlet/src/main/webapp/html/moderation/includes/moderationActionButtons.jspf
- frontend/sw360-portlet/src/main/webapp/html/moderation/view.jsp
Added links to moderation requests in MyTaskAssignments and MyTaskSubmissions portlets. Also enabled moderators to open and review already closed moderation requests
Closes #93
> Links To Moderation Requests In MyTask* Portlets

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/admin/VendorPortlet.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/licenses/LicensesPortlet.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
- frontend/sw360-portlet/src/main/webapp/html/projects/includes/projects/clearingStatus.jspf
- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Constants.java
fix for #325 based on user feedback
> Added Download Spreadsheet button to project's Clearing Status tab

- frontend/sw360-portlet/pom.xml
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/hooks/BuildInfoForVelocityProviderHook.java
- frontend/sw360-portlet/src/main/resources/portal.properties
- frontend/sw360-theme/src/main/webapp/templates/portal_normal.vm
- pom.xml
> added version info to sw360 theme template

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/DisplayUserEmail.java
- frontend/sw360-portlet/src/main/webapp/WEB-INF/customTags.tld
- frontend/sw360-portlet/src/main/webapp/html/projects/view.jsp
- deferred calculation of release clearing state summaries by loading them asynchronously via ajax
- disabled loading of user names by emails for display in the table
> Improved Loading Time of the Project List Page

- backend/src/src-licenses/pom.xml
- backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/LicenseHandler.java
- backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/db/LicenseDatabaseHandler.java
- backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/tools/SpdxConnector.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/admin/DatabaseSanitation.java
- frontend/sw360-portlet/src/main/webapp/html/admin/databaseSanitation/view.jsp
- libraries/lib-datahandler/src/main/thrift/licenses.thrift
This adds a button in the admin db ui which allows an admin to import all SPDX licenses into the DB
> feat(admin): allow to import all SPDX licenses

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/moderation/ModerationPortlet.java
- frontend/sw360-portlet/src/main/webapp/html/projects/includes/detailOverview.jspf
- frontend/sw360-portlet/src/main/webapp/html/projects/includes/projects/administration.jspf
- frontend/sw360-portlet/src/main/webapp/html/projects/includes/projects/basicInfo.jspf
- frontend/sw360-portlet/src/main/webapp/html/projects/includes/projects/summary.jspf
- libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ProjectExporter.java
- libraries/lib-datahandler/src/main/thrift/projects.thrift
- Add project owner, owner accounting unit, and owner group fields
- Reorganize display and edit pages for project
- Fix display of project clearing details in project moderation view
> Add project owner, owner accounting unit, and owner group fields

- frontend/sw360-portlet/src/main/webapp/html/components/includes/components/clearingStatus.jspf
- frontend/sw360-portlet/src/main/webapp/html/components/includes/components/editBasicInfo.jspf
- frontend/sw360-portlet/src/main/webapp/html/components/includes/components/summary.jspf
- libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ComponentExporter.java
- libraries/lib-datahandler/src/main/thrift/components.thrift
- Add component owner, owner accounting unit, and owner group fields
- Reorganize display and edit pages for component
> Add component owner, owner accounting unit, and owner group fields

- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/ThriftEnumUtils.java
- libraries/lib-datahandler/src/main/thrift/components.thrift
- add component types INNER_SOURCE and SERVICE 
- shorten display names of the existing component types
closes #350
> Add Component Types INNER_SOURCE and SERVICE and rename existing types

- backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ModerationDatabaseHandler.java
- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/permissions/DocumentPermissions.java
- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/permissions/ProjectPermissions.java
- libraries/lib-datahandler/src/test/java/org/eclipse/sw360/datahandler/permissions/ProjectPermissionsTest.java
- libraries/lib-datahandler/src/test/java/org/eclipse/sw360/datahandler/permissions/ReleasePermissionsTest.java
- libraries/lib-datahandler/src/test/java/org/eclipse/sw360/datahandler/permissions/jgivens/ThenHighestAllowedAction.java
- libraries/lib-datahandler/src/test/java/org/eclipse/sw360/datahandler/permissions/jgivens/WhenComputePermissions.java
dev(projects): restrict project editing to clearing admins of the project group
> Restrict project editing to clearing admins of the project group

- Rakefile
- sw360dev.Dockerfile
the previously set volume for the `.m2`-repository-cache was not valid.
(this fixes a feature which is apparently only used by me)
> chores(rake): fix minor bug in docker call

- backend/src/src-cvesearch/pom.xml
- backend/src/src-schedule/pom.xml
- backend/svc/svc-cvesearch/pom.xml
- backend/svc/svc-schedule/pom.xml
replace groupId org.eclipse with org.eclipse.sw360
> fix wrong groupId in some pom files

- frontend/sw360-portlet/src/main/webapp/html/utils/includes/attachmentsDetail.jsp
Minor UI improvement:
old version:
new version:
> fix(ui): attachment detail list was corrupted

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/DisplayMapOfEmailStringSets.java
- frontend/sw360-portlet/src/main/webapp/WEB-INF/customTags.tld
Sorry, I have overlooked this while preparing the contribution.
> fix(groupId): The file `DisplayMapOfEmailStringSets.java` was added under the wrong groupId

- backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/LicenseInfoGenerator.java
- backend/src/src-vulnerabilities/src/main/java/org/eclipse/sw360/vulnerabilities/VulnerabilityHandler.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/admin/VendorPortlet.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/licenses/LicensesPortlet.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
- frontend/sw360-portlet/src/main/webapp/html/components/detail.jsp
- frontend/sw360-portlet/src/main/webapp/html/components/detailRelease.jsp
- frontend/sw360-portlet/src/main/webapp/html/components/edit.jsp
- frontend/sw360-portlet/src/main/webapp/html/components/editRelease.jsp
- frontend/sw360-portlet/src/main/webapp/html/projects/detail.jsp
- frontend/sw360-portlet/src/main/webapp/html/projects/edit.jsp
This PR includes `/html/utils/includes/logError.jspf` on multiple jsp files, to render error messages. This also adds correct response codes to failed requests.
Is related to https://github.com/sw360/sw360portal/issues/109
> feat(ui): in detail and edit.jsp pages: error handling for useBeans

- backend/src/src-licenseinfo/src/test/java/org/eclipse/sw360/licenseinfo/parsers/SPDXParserTest.java
- libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ReleaseExporter.java
- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java
- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/UncheckedSW360Exception.java
Clean up neglected review comments on PR #398
> chore(export): clean up the code merged with PR #398

- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/CommonUtils.java
This fixes a NullPointerException thrown at CommonUtils.java:645 when opening a moderation request
> fix(moderation): fix NullPointerException in moderation

- frontend/sw360-portlet/src/main/webapp/html/projects/includes/linkedProjects.jspf
- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/ThriftEnumUtils.java
- libraries/lib-datahandler/src/main/thrift/sw360.thrift
> dev(releases): add some more release relationship types

- .travis.yml
closes #471 
**EDIT by @alexbrdn**: corrected referenced issue number
> fix(travis): start couchdb explicitly

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
fixes a bug introduced by #461
> fix(project): LicenseInfo Generation page doesn't show any attachments

- libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ExcelExporter.java
fix an error in spreadsheet export
> fix(export): spreadsheet export couldn't auto-size columns

- backend/src-common/src/main/java/org/eclipse/sw360/components/summary/LicenseSummary.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/Sw360Portlet.java
*removed case sensitive license search
*added search also in shortname
related to
#478 #348 #458
> fix(license): make search for licenses case insensitive 

- frontend/sw360-portlet/src/main/webapp/css/sw360.css
- frontend/sw360-portlet/src/main/webapp/html/admin/bulkReleaseEdit/view.jsp
- frontend/sw360-portlet/src/main/webapp/html/admin/user/view.jsp
- frontend/sw360-portlet/src/main/webapp/html/admin/vendors/view.jsp
- frontend/sw360-portlet/src/main/webapp/html/ecc/view.jsp
- frontend/sw360-portlet/src/main/webapp/html/search/view.jsp
> style(ui): Changed text colour for filter values

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectRepository.java
- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectSearchHandler.java
- backend/src/src-search/src/main/java/org/eclipse/sw360/search/db/DatabaseSearchHandler.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
- frontend/sw360-portlet/src/main/webapp/html/projects/view.jsp
- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/lucene/LuceneAwareDatabaseConnector.java
- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/permissions/ProjectPermissions.java
- libraries/lib-datahandler/src/test/java/org/eclipse/sw360/datahandler/permissions/jgivens/WhenComputeVisibility.java
* added input field and frontend handling for version in project filters
* added version field to lucene index definition function for projects
* refactored guava stream to j8 stream
* removed unused private method in ProjectPortlet
* removed unused loggers
* removed unused imports
> feat(projects): add possibility to filter project list for versions

- frontend/sw360-portlet/src/main/webapp/html/components/includes/components/clearingStatus.jspf
- frontend/sw360-portlet/src/main/webapp/html/components/includes/releases/editReleaseInformation.jspf
- frontend/sw360-portlet/src/main/webapp/html/components/includes/releases/summaryRelease.jspf
- frontend/sw360-portlet/src/main/webapp/html/projects/includes/projects/clearingStatus.jspf
- frontend/sw360-portlet/src/main/webapp/html/utils/ajax/linkedReleasesAjax.jsp
- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/ThriftEnumUtils.java
Renaming UI items for component clearing state ("Report Approved") and project mainline state ("Project Mainline state").
closes #491
> chore(ui): renaming UI items issue #491

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
- frontend/sw360-portlet/src/main/webapp/html/components/edit.jsp
- frontend/sw360-portlet/src/main/webapp/html/components/includes/components/editBasicInfo.jspf
- frontend/sw360-portlet/src/main/webapp/html/projects/edit.jsp
- frontend/sw360-portlet/src/main/webapp/html/utils/includes/mapEdit.jspf
- frontend/sw360-portlet/src/main/webapp/html/utils/includes/requirejs.jspf
- frontend/sw360-portlet/src/main/webapp/js/components/includes/vendors/addVendor.js
- frontend/sw360-portlet/src/main/webapp/js/modules/linkListDialog.js
- frontend/sw360-portlet/src/main/webapp/js/modules/sw360Validate.js
* refactored javascript to be in require block so that jquery and its validation plugin are available when registering the form for validation
fixes sw360/sw360portal#543
First commit is the same as on https://github.com/sw360/sw360portal/pull/528 but I needed the code. So only the commit 9b7ecda has to be reviewed here.
> fix(projects): "Update Project" button is working again

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/entitlement/ProjectModerator.java
- backend/src-common/src/test/java/org/eclipse/sw360/components/summary/ProjectSummaryTest.java
- backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ProjectModerationRequestGenerator.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortletUtils.java
- frontend/sw360-portlet/src/main/webapp/css/sw360.css
- frontend/sw360-portlet/src/main/webapp/html/projects/includes/detailOverview.jspf
- frontend/sw360-portlet/src/main/webapp/html/projects/includes/projects/basicInfo.jspf
- frontend/sw360-portlet/src/main/webapp/html/projects/includes/projects/vulnerabilities.jspf
- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/Moderator.java
- libraries/lib-datahandler/src/main/thrift/projects.thrift
- add a flag for enabling Security Vulnerability Monitoring to projects
- change display of vulnerabilities counts to have red background only when SVM is enabled
- fix generating and applying a moderation request with boolean and int32 fields
> feat(svm): add a flag field to projects to explicitly enable VM

- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/ThriftEnumUtils.java
fix(moderation): fix the NullPointerException in ThriftEnumUtils thrown when moderator declines a request
closes sw360/sw360portal#560
> fix(moderation): fix the NullPointerException in ThriftEnumUtils

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortletUtils.java
> fix(attachments): could not be added if no attachments exists

- backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ModerationDatabaseHandler.java
Closes sw360/sw360portal#582
Closes sw360/sw360portal#585
> fix(moderation): fix bug in license moderation

- frontend/sw360-portlet/pom.xml
- frontend/sw360-portlet/src/main/webapp/WEB-INF/liferay-portlet.xml
- frontend/sw360-portlet/src/main/webapp/css/dataTable_Siemens.css
- frontend/sw360-portlet/src/main/webapp/css/print.css
- frontend/sw360-portlet/src/main/webapp/html/admin/vendors/view.jsp
- frontend/sw360-portlet/src/main/webapp/html/components/includes/components/clearingStatus.jspf
- frontend/sw360-portlet/src/main/webapp/html/components/includes/components/vulnerabilities.jspf
- frontend/sw360-portlet/src/main/webapp/html/components/view.jsp
- frontend/sw360-portlet/src/main/webapp/html/ecc/view.jsp
- frontend/sw360-portlet/src/main/webapp/html/licenses/view.jsp
- frontend/sw360-portlet/src/main/webapp/html/moderation/view.jsp
- frontend/sw360-portlet/src/main/webapp/html/projects/includes/projects/clearingStatus.jspf
- frontend/sw360-portlet/src/main/webapp/html/projects/view.jsp
- frontend/sw360-portlet/src/main/webapp/html/utils/includes/requirejs.jspf
- frontend/sw360-portlet/src/main/webapp/html/vulnerabilities/view.jsp
- Change print layout for all pages
- Add print button to data tables to export all data
- Catch CTRL+P and print all entries 
closes sw360/sw360portal#502
> feat(ui): format print page and add print button to datatable

- backend/src-common/src/main/java/org/eclipse/sw360/components/summary/ReleaseSummary.java
- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentRepository.java
- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
- backend/src/src-components/src/main/java/org/eclipse/sw360/components/ComponentHandler.java
- backend/src/src-components/src/test/java/org/eclipse/sw360/components/db/ComponentDatabaseHandlerTest.java
- backend/src/src-projects/src/main/java/org/eclipse/sw360/projects/ProjectHandler.java
- backend/src/src-vulnerabilities/src/main/java/org/eclipse/sw360/vulnerabilities/VulnerabilityHandler.java
- backend/src/src-vulnerabilities/src/main/java/org/eclipse/sw360/vulnerabilities/db/VulnerabilityDatabaseHandler.java
- backend/src/src-vulnerabilities/src/main/java/org/eclipse/sw360/vulnerabilities/db/VulnerabilityRelationRepository.java
- backend/src/src-vulnerabilities/src/main/java/org/eclipse/sw360/vulnerabilities/db/VulnerabilityRepository.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/CustomFieldHelper.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortletUtils.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortletUtils.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortletUtils.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/vulnerabilities/VulnerabilitiesPortlet.java
- frontend/sw360-portlet/src/main/webapp/html/utils/includes/usingReleasesTable.jspf
- frontend/sw360-portlet/src/main/webapp/html/vulnerabilities/summary.jspf
- frontend/sw360-portlet/src/main/webapp/html/vulnerabilities/view.jsp
- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/CommonUtils.java
- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/DatabaseRepository.java
- libraries/lib-datahandler/src/main/thrift/vulnerabilities.thrift
https://github.com/sw360/sw360portal/issues/411
https://github.com/sw360/sw360portal/issues/574
> feat(vulnerabilities): Improve vulnerabilities overview page to speed up loading time

- frontend/sw360-portlet/src/main/resources/portal.properties
> feat(ui): Make Liferay session expire after 30 minutes

- backend/src/src-cvesearch/src/main/java/org/eclipse/sw360/cvesearch/datasource/CveSearchWrapper.java
- backend/src/src-cvesearch/src/main/java/org/eclipse/sw360/cvesearch/datasource/heuristics/SearchLevels.java
- backend/src/src-cvesearch/src/main/java/org/eclipse/sw360/cvesearch/service/CveSearchHandler.java
- backend/src/src-cvesearch/src/main/resources/sw360.properties
- backend/src/src-cvesearch/src/test/resources/sw360.properties
- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/CommonUtils.java
- libraries/lib-datahandler/src/test/java/org/eclipse/sw360/datahandler/common/CommonUtilsTest.java
Allows for configuring the CVE search using sw360.properties
> feat(vulnerabilities): Make CVE search configurable

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/licenses/LicensesPortlet.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/moderation/ModerationPortlet.java
- frontend/sw360-portlet/src/main/webapp/html/components/includes/releases/editReleaseECCInformation.jspf
- add warning message on the release edit page for ECC data.
- the message is visible only if the user is not an ECC Admin
closes sw360/sw360portal#339
> chore(components): Show moderation request warning when updating ECC data

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projectimport/ProjectImportConstants.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projectimport/ProjectImportPortlet.java
- frontend/sw360-portlet/src/main/webapp/WEB-INF/portlet.xml
- frontend/sw360-portlet/src/main/webapp/html/projects/import.jsp
- frontend/sw360-portlet/src/test/java/org/eclipse/sw360/portal/portlets/projectimport/ProjectImportPortletTest.java
- libraries/lib-datahandler/src/main/thrift/bdpimport.thrift
Must be considered with PR https://github.com/sw360/sw360bdpImportService/pull/4 from bdpImportService
> feat(bdpimport): Allow user to search for BDP projects instead of loading them all

- frontend/sw360-portlet/src/main/webapp/html/moderation/projects/merge.jsp
- remove z character for project moderation requests
closes sw360/sw360portal#672
> chore(moderation): remove z character for project moderation requests

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
- fix license info generation null pointer exception
(set createdon and createdteam to empty if null)
> fix(projects): fix NullPointerException when preparing LicenseInfo generation page

- frontend/sw360-portlet/src/main/webapp/html/licenses/includes/detailRisks.jspf
change the risk text for licenses
**from** 
> No license risks known
**to**
> No license risks analysis available.
> chore(license): Change risk text to No license risks analysis available

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortletUtils.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortletUtils.java
- frontend/sw360-portlet/src/main/webapp/html/components/edit.jsp
- frontend/sw360-portlet/src/main/webapp/html/components/editRelease.jsp
- frontend/sw360-portlet/src/main/webapp/html/components/includes/components/summary.jspf
- frontend/sw360-portlet/src/main/webapp/html/components/mergeComponent.jsp
- frontend/sw360-portlet/src/main/webapp/html/projects/edit.jsp
- frontend/sw360-portlet/src/main/webapp/html/utils/includes/editExternalIds.jsp
- libraries/lib-datahandler/src/main/thrift/components.thrift
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
- add external ids to components (view/edit/merge)
- add external id in the edit page of the project
> feat(ui): extend external ids for projects and components

- frontend/sw360-portlet/src/main/webapp/html/components/includes/components/editBasicInfo.jspf
- frontend/sw360-portlet/src/main/webapp/html/components/includes/components/summary.jspf
- frontend/sw360-portlet/src/main/webapp/html/components/mergeComponent.jsp
- frontend/sw360-portlet/src/main/webapp/html/projects/includes/projects/basicInfo.jspf
- frontend/sw360-portlet/src/main/webapp/html/projects/includes/projects/summary.jspf
- libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ComponentExporter.java
- libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ProjectExporter.java
- libraries/lib-datahandler/src/main/thrift/components.thrift
- libraries/lib-datahandler/src/main/thrift/projects.thrift
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
- add new field 'Owner Country' to projects and components
> feat(projects,components): add new field owner country to data model

- libraries/lib-datahandler/src/main/thrift/components.thrift
- thrift id changed for component external id
(from value 30 to value 31)
> fix(thrift): change thrift id for external ids

- frontend/sw360-portlet/pom.xml
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortletUtils.java
- frontend/sw360-portlet/src/main/webapp/html/components/includes/components/vulnerabilities.jspf
- frontend/sw360-portlet/src/main/webapp/html/components/includes/releases/vulnerabilities.jspf
- frontend/sw360-portlet/src/main/webapp/html/projects/import.jsp
- frontend/sw360-portlet/src/main/webapp/html/projects/includes/projects/vulnerabilities.jspf
- frontend/sw360-portlet/src/main/webapp/html/utils/includes/requirejs.jspf
- frontend/sw360-portlet/src/main/webapp/js/utils/includes/vulnerabilityModal.js
* Concerns the vulnerability tables the following portlets: projects/component/releases
* See screenshots for example
* Multiselect (now working with shift) was also added to Project Import
> feat(vulnerabilities): Allow editing of multiple vulnerabilities concurrently

- frontend/sw360-portlet/src/main/webapp/html/components/detail.jsp
- frontend/sw360-portlet/src/main/webapp/html/components/detailRelease.jsp
- frontend/sw360-portlet/src/main/webapp/html/components/includes/components/clearingStatus.jspf
- frontend/sw360-portlet/src/main/webapp/html/components/includes/components/editBasicInfo.jspf
- frontend/sw360-portlet/src/main/webapp/html/components/view.jsp
- frontend/sw360-portlet/src/main/webapp/html/homepage/signup/view.jsp
- frontend/sw360-portlet/src/main/webapp/html/licenses/detail.jsp
- frontend/sw360-portlet/src/main/webapp/html/licenses/includes/detailSummary.jspf
- frontend/sw360-portlet/src/main/webapp/html/moderation/components/delete.jsp
- frontend/sw360-portlet/src/main/webapp/html/moderation/components/merge.jsp
- frontend/sw360-portlet/src/main/webapp/html/projects/view.jsp
- frontend/sw360-portlet/src/main/webapp/html/utils/includes/attachmentsDetail.jsp
- frontend/sw360-portlet/src/main/webapp/html/utils/includes/usingComponentsTable.jspf
- frontend/sw360-portlet/src/main/webapp/html/utils/includes/usingProjectsTable.jspf
- frontend/sw360-portlet/src/main/webapp/html/utils/includes/usingReleasesTable.jspf
* Added <sw360:out/> to string variables that could contain quotes
> fix(frontend): Protect quotes in text variables

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
show delivery start information for projects
sw360/sw360portal#728
> chore(rest): show delivery date (deliverystart) for projects

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/Sw360ComponentService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/LicenseController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vulnerability/Sw360VulnerabilityService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vulnerability/VulnerabilityController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vulnerability/VulnerabilityDTOResourceProcessor.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vulnerability/VulnerabilityResourceProcessor.java
- rest/resource-server/src/main/resources/application.yml
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ApiSpecTest.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
new added endpoints are:
- search by name for
- projects
- component
- search by sha1 for
- releases
- vulnerabilities
- replace licenses at release
> feat(rest): New endpoints for the rest api

- rest/resource-server/src/docs/asciidoc/api-guide.adoc
- rest/resource-server/src/docs/asciidoc/index.adoc
- rest/resource-server/src/docs/asciidoc/vulnerabilities.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/VulnerabilitySpecTest.java
- changed subtitle and hierarchy level
- added status code
- added chapter 'Token'
- added some fields for components and projects
> chore(rest): Update for REST API documentation

- frontend/sw360-portlet/src/main/webapp/html/projects/includes/projects/basicInfo.jspf
- frontend/sw360-portlet/src/main/webapp/js/utils/includes/searchAndSelectIds.js
(no security responsibles)
- the checkbox is disabled
- the checkbox is set to uncheck
(filled security responsibles)
- the checkbox is activated
- user can check and uncheck the checkbox
closes sw360/sw360portal#548
> fix(projects): security monitoring checkbox behavior (security responsibles)

- frontend/sw360-portlet/src/main/webapp/html/utils/includes/searchAndSelectLicenses.jsp
- frontend/sw360-portlet/src/main/webapp/html/utils/includes/searchAndSelectUsers.jsp
- frontend/sw360-portlet/src/main/webapp/html/utils/includes/searchLicenses.jsp
- frontend/sw360-portlet/src/main/webapp/html/utils/includes/searchUsers.jsp
- frontend/sw360-portlet/src/main/webapp/js/utils/includes/searchAndSelectIds.js
- new button 'reset'
- removes checked attribute for input elements
- perform a new search for users
closes sw360/sw360portal#119
> chore(ui): add reset button in user search dialog

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
provides search functionality for projects and components
- search by type (project type, component type)
- /api/projects?type=<>
- /api/components?type=<>
e.g.
```
https://localhost:8443/resource/api/projects?type=PRODUCT
https://localhost:8443/resource/api/projects?type=INNER_SOURCE
https://localhost:8443/resource/api/components?type=OSS
https://localhost:8443/resource/api/components?type=INNER_SOURCE
```
closes sw360/sw360portal#730
> chore(rest): add search by type for projects and components

- frontend/sw360-portlet/src/main/webapp/html/components/editRelease.jsp
- frontend/sw360-portlet/src/main/webapp/html/components/includes/releases/editCommercialDetails.jspf
- frontend/sw360-portlet/src/main/webapp/html/components/includes/releases/editReleaseClearingInformation.jspf
- frontend/sw360-portlet/src/main/webapp/html/components/includes/releases/editReleaseECCInformation.jspf
- frontend/sw360-portlet/src/main/webapp/html/components/includes/releases/editReleaseInformation.jspf
- frontend/sw360-portlet/src/main/webapp/html/projects/includes/projects/administrationEdit.jspf
- add YYYY-MM-DD pattern to all input datepicker
`pattern="\d{4}-\d{1,2}-\d{1,2}"`
closes sw360/sw360portal#174
> chore(ui): add pattern format to all input datepicker

- frontend/sw360-portlet/src/main/webapp/css/sw360.css
- frontend/sw360-portlet/src/main/webapp/html/components/detailRelease.jsp
Please check if everything is fine. And let me know if I should put my CSS elements in a different file.
closes sw360/sw360portal#738
> feat(ui): added clearing state to dropdown

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/AttachmentPortletUtils.java
- libraries/commonIO/src/main/java/org/eclipse/sw360/commonIO/AttachmentFrontendUtils.java
- rest/resource-server/pom.xml
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/attachment/Sw360AttachmentService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/Sw360ComponentService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/licenseinfo/LicenseInfoController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/licenseinfo/LicenseInfoResourceProcessor.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/licenseinfo/Sw360LicenseInfoService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java
- rest/resource-server/src/main/resources/application.yml
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ApiSpecTest.java
- New endpoints to upload an attachment to a project, component or release
- New endpoints to download an attachment of a project, component or release
- New endpoint to generate license information file for a project and download it (TODO: Implement method to determine excluded licenses)
- New endpoint to download all clearing reports of a project
closes sw360/sw360portal#767
> feat(rest): new endpoints to upload and download attachments

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/signup/SignupPortletUtils.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/users/HttpServletRequestAdapter.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/users/LandingPageAction.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/users/OrganizationHelper.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/users/PortletRequestAdapter.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/users/RequestAdapter.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/users/SSOAutoLogin.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/users/UserPortletUtils.java
- frontend/sw360-portlet/src/main/resources/orgmapping.properties
- frontend/sw360-portlet/src/main/resources/portal.properties
- frontend/sw360-portlet/src/main/resources/sw360.properties
- make SSOAutoLogin actually work
- add possibility to map organizations from external org codes to Liferay organizations (adapted from ldapOrganizationMappingExt)
- Create Liferay organizations and users when necessary, (re-)assign user to org when necessary.
> feat: make SSOAutoLogin actually work

- frontend/sw360-portlet/src/main/webapp/html/components/mergeComponent.jsp
> Component merge wizzard check that components' ids are not same.

- frontend/sw360-portlet/src/main/webapp/js/main.js
> fix(ui): delete button colors

- backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/db/LicenseDatabaseHandler.java
- backend/src/src-licenses/src/test/java/org/eclipse/sw360/licenses/LicenseHandlerTest.java
- frontend/sw360-portlet/src/main/webapp/html/licenses/includes/editDetailSummary.jspf
- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/thrift/ThriftValidate.java
- add validate function to ThriftValidate.java
- verify license id / short name in addLicense and updateLicense
closes sw360/sw360portal#329
> fix(license): validate license id and short name
