sw360/sw360portal

backend/src-common/src/main/java/com/siemens/sw360/datahandler/db/ComponentDatabaseHandler.java
backend/src/src-components/src/test/java/com/siemens/sw360/components/db/ComponentDatabaseHandlerTest.java

My components has had issues with loading up. Now the search for
components where the user has created a release has been removed. It is
useful but benefit is not that large to tolerate long load times.

(fix) loading of my components

---

backend/pom.xml

The file `/etc/maven/settings.xml` should already contain the credentials.

remove hardcoded tomcat password

---

.travis.yml
scripts/install-thrift.sh

This script adds travis support for SW360. On travis it calls `mvn install` which builds everything and also executes the tests.
Required packages which were missing
- couchdb
- thrift
*TODO:* it uses oracle jdk 8?

add travis support

---

backend/src-common/src/main/java/com/siemens/sw360/datahandler/db/ProjectDatabaseHandler.java
frontend/sw360-portlet/src/main/java/com/siemens/sw360/portal/common/PortalConstants.java
frontend/sw360-portlet/src/main/java/com/siemens/sw360/portal/portlets/Sw360Portlet.java
frontend/sw360-portlet/src/main/java/com/siemens/sw360/portal/portlets/moderation/ModerationPortlet.java
frontend/sw360-portlet/src/main/java/com/siemens/sw360/portal/portlets/projects/ProjectPortlet.java
frontend/sw360-portlet/src/main/webapp/html/projects/includes/linkedProjects.jspf
frontend/sw360-portlet/src/main/webapp/html/utils/includes/linkedReleaseDetails.jspf
libraries/lib-datahandler/src/main/java/com/siemens/sw360/datahandler/common/SW360Utils.java
libraries/lib-datahandler/src/main/thrift/projects.thrift

- Added display of inherited linked projects (linked projects of linked projects) analogously to the display of inherited linked releases.
- Removed repetitive field labels in favor of table column headers when displaying linked releases and linked projects
Closes #131

Displaying linked projects of linked projects

---

backend/src-common/src/main/java/com/siemens/sw360/datahandler/db/ComponentDatabaseHandler.java
backend/src-common/src/main/java/com/siemens/sw360/datahandler/db/ProjectDatabaseHandler.java
libraries/lib-datahandler/src/main/java/com/siemens/sw360/datahandler/couchdb/AttachmentConnector.java
libraries/lib-datahandler/src/test/java/com/siemens/sw360/datahandler/couchdb/AttachmentConnectorTest.java

- fixed: attachment content is deleted from sw360attachments db when some attachment property gets updated.
- fixed: sha1 is not computed when a new component, release, or project is created with attachments 
closes #154

Fixed deletion of attachment content on update

---

frontend/sw360-portlet/src/main/webapp/css/sw360.css
frontend/sw360-portlet/src/main/webapp/html/utils/includes/attachmentsDetail.jsp

fix(#151): display hash with `<span>` instead of `<input>`

---

backend/src/src-licenseinfo/src/main/java/com/siemens/sw360/licenseinfo/parsers/SPDXParser.java
backend/src/src-licenseinfo/src/test/java/com/siemens/sw360/licenseinfo/TestHelper.java
backend/src/src-licenseinfo/src/test/java/com/siemens/sw360/licenseinfo/parsers/CLIParserTest.java
backend/src/src-licenseinfo/src/test/java/com/siemens/sw360/licenseinfo/parsers/SPDXParserTest.java
backend/src/src-licenseinfo/src/test/resources/SPDXRdfExample-v2.0.rdf

PR contains tests for SPDX document parser used for the licenseInfo service. 
It also changes the SPDX parser behavior so that it takes into account the attachment type when deciding whether to parse a file.

spdx to disclosure document: tests

---

backend/src-common/src/main/java/com/siemens/sw360/components/summary/ComponentSummary.java
backend/src-common/src/main/java/com/siemens/sw360/components/summary/ProjectSummary.java
backend/src-common/src/main/java/com/siemens/sw360/components/summary/ReleaseSummary.java
backend/src-common/src/main/java/com/siemens/sw360/datahandler/db/ComponentDatabaseHandler.java
backend/src-common/src/main/java/com/siemens/sw360/datahandler/db/ProjectDatabaseHandler.java
backend/src-common/src/main/java/com/siemens/sw360/datahandler/db/ProjectRepository.java
backend/src/src-components/src/main/java/com/siemens/sw360/components/ComponentHandler.java
backend/src/src-components/src/test/java/com/siemens/sw360/components/db/ComponentDatabaseHandlerTest.java
backend/src/src-projects/src/main/java/com/siemens/sw360/projects/ProjectHandler.java
frontend/sw360-portlet/src/main/java/com/siemens/sw360/portal/common/PortalConstants.java
frontend/sw360-portlet/src/main/java/com/siemens/sw360/portal/portlets/components/ComponentPortlet.java
frontend/sw360-portlet/src/main/java/com/siemens/sw360/portal/portlets/projects/ProjectPortlet.java
frontend/sw360-portlet/src/main/java/com/siemens/sw360/portal/portlets/projects/ProjectPortletUtils.java
frontend/sw360-portlet/src/main/webapp/css/sw360.css
frontend/sw360-portlet/src/main/webapp/html/components/view.jsp
frontend/sw360-portlet/src/main/webapp/html/projects/view.jsp
libraries/exporters/src/main/java/com/siemens/sw360/exporter/ComponentExporter.java
libraries/exporters/src/main/java/com/siemens/sw360/exporter/ExcelExporter.java
libraries/exporters/src/main/java/com/siemens/sw360/exporter/ExcelSubTable.java
libraries/exporters/src/main/java/com/siemens/sw360/exporter/ExporterHelper.java
libraries/exporters/src/main/java/com/siemens/sw360/exporter/LicenseExporter.java
libraries/exporters/src/main/java/com/siemens/sw360/exporter/ProjectExporter.java
libraries/exporters/src/main/java/com/siemens/sw360/exporter/ReleaseExporter.java
libraries/exporters/src/main/java/com/siemens/sw360/exporter/SubTable.java
libraries/exporters/src/main/java/com/siemens/sw360/exporter/VendorExporter.java
libraries/exporters/src/test/java/com/siemens/sw360/exporter/ProjectExporterTest.java
libraries/lib-datahandler/src/main/java/com/siemens/sw360/datahandler/common/SW360Utils.java
libraries/lib-datahandler/src/main/thrift/projects.thrift

For projects and components: closes #223
* possibility to extend excel export with (directly linked) releases
* one line per project-release resp. component-release combination 
* (almost) complete export of project, component and releas
* vendor, ClearingInfo, COTSDetails in separate columns 
* export respects filter (but not keyword search)
* export button only enabled when filter parameters and view consistent

Excel export extended by releases

---

backend/src/src-licenseinfo/src/main/java/com/siemens/sw360/licenseinfo/parsers/SPDXParser.java
backend/src/src-licenseinfo/src/test/java/com/siemens/sw360/licenseinfo/parsers/SPDXParserTest.java

The `AttachmentType.Document` was previously excluded
In the effort to solve this bug, also some code was refactored.

fix: SPDX licenseinfo should also use `Document` AttachmentType

---

backend/src/src-licenseinfo/src/main/java/com/siemens/sw360/licenseinfo/LicenseInfoHandler.java
backend/src/src-licenseinfo/src/main/java/com/siemens/sw360/licenseinfo/parsers/SPDXParser.java
backend/src/src-licenseinfo/src/test/java/com/siemens/sw360/licenseinfo/parsers/SPDXParserTest.java

Only extracted licensetexts were used previously, as mentioned in the comment https://github.com/sw360/sw360portal/pull/207#issuecomment-243743512

LicenseInfo: also include missing licenses for SPDX

---

backend/src-common/src/main/java/com/siemens/sw360/datahandler/db/CustomPropertiesRepository.java
backend/src/src-licenses/src/main/java/com/siemens/sw360/licenses/LicenseHandler.java
backend/src/src-licenses/src/main/java/com/siemens/sw360/licenses/db/LicenseDatabaseHandler.java
frontend/sw360-portlet/src/main/java/com/siemens/sw360/portal/portlets/admin/ComponentUploadPortlet.java
frontend/sw360-portlet/src/main/java/com/siemens/sw360/portal/tags/DisplayMap.java
frontend/sw360-portlet/src/main/webapp/WEB-INF/customTags.tld
frontend/sw360-portlet/src/main/webapp/css/sw360.css
frontend/sw360-portlet/src/main/webapp/html/licenses/includes/detailTodos.jspf
libraries/commonIO/pom.xml
libraries/commonIO/src/main/java/com/siemens/sw360/commonIO/ConvertRecord.java
libraries/commonIO/src/main/java/com/siemens/sw360/commonIO/TypeMappings.java
libraries/commonIO/src/test/java/com/siemens/sw360/commonIO/ConvertRecordTest.java
libraries/exporters/src/main/java/com/siemens/sw360/exporter/ZipTools.java
libraries/importers/license-importer/src/main/java/com/siemens/sw360/importer/LicenseImporter.java
libraries/lib-datahandler/src/main/java/com/siemens/sw360/datahandler/common/CommonUtils.java
libraries/lib-datahandler/src/main/java/com/siemens/sw360/datahandler/thrift/ThriftUtils.java
libraries/lib-datahandler/src/main/thrift/licenses.thrift
libraries/lib-datahandler/src/main/thrift/sw360.thrift

This PR allows to import lics archives with licenses that have custom properties. For that a new table is introduced that is contained as csv file hi the archive.

lics: import custom properties

---

backend/src/src-moderation/src/main/java/com/siemens/sw360/moderation/ModerationHandler.java
build-configuration/resources/couchdb.properties
frontend/sw360-portlet/src/main/java/com/siemens/sw360/portal/common/PortalConstants.java
frontend/sw360-portlet/src/main/java/com/siemens/sw360/portal/portlets/Sw360Portlet.java
frontend/sw360-portlet/src/main/java/com/siemens/sw360/portal/portlets/moderation/ModerationPortlet.java
frontend/sw360-portlet/src/main/webapp/css/sw360.css
frontend/sw360-portlet/src/main/webapp/html/licenses/includes/detailOverview.jspf
frontend/sw360-portlet/src/main/webapp/html/moderation/components/delete.jsp
frontend/sw360-portlet/src/main/webapp/html/moderation/components/merge.jsp
frontend/sw360-portlet/src/main/webapp/html/moderation/includes/moderationActionButtons.jspf
frontend/sw360-portlet/src/main/webapp/html/moderation/includes/moderationActions.jspf
frontend/sw360-portlet/src/main/webapp/html/moderation/licenses/merge.jsp
frontend/sw360-portlet/src/main/webapp/html/moderation/projects/delete.jsp
frontend/sw360-portlet/src/main/webapp/html/moderation/projects/merge.jsp
frontend/sw360-portlet/src/main/webapp/html/moderation/releases/delete.jsp
frontend/sw360-portlet/src/main/webapp/html/moderation/releases/merge.jsp
frontend/sw360-portlet/src/main/webapp/html/moderation/users/merge.jsp
frontend/sw360-portlet/src/main/webapp/html/moderation/view.jsp
frontend/sw360-portlet/src/main/webapp/html/projects/detail.jsp
frontend/sw360-portlet/src/main/webapp/html/projects/detailOverview.jspf
frontend/sw360-portlet/src/main/webapp/html/projects/includes/linkedProjects.jspf
libraries/lib-datahandler/src/main/java/com/siemens/sw360/datahandler/common/Moderator.java
libraries/lib-datahandler/src/main/thrift/moderation.thrift
libraries/lib-datahandler/src/main/thrift/sw360.thrift

set lucene.limit to 150  …
* get a maximum of 150 results when using the filter in project and component portlet
* has to be tested: is speed still ok?
* closes #221 if speed is ok
avoid moderation request zombie  …
* if last moderator wants to unsubscribe, pop-up - not allowed
* closes #114
* merge only after #230 and use ..../jquery-confirm.min.css and ../jquery-confirm.min.js from #230

increase lucene filter limit and avoid moderation request zombie

---

frontend/sw360-portlet/src/main/webapp/html/projects/includes/projects/summary.jspf
frontend/sw360-portlet/src/main/webapp/html/projects/view.jsp

Display version of project in projects view ￼…
* closes #220
Display external ids in project details view ￼…
* closes #224

Add project version to view and external id to details view

---

backend/src-common/src/main/java/com/siemens/sw360/datahandler/db/ComponentDatabaseHandler.java
backend/src-common/src/main/java/com/siemens/sw360/datahandler/db/ProjectDatabaseHandler.java
backend/src/src-components/src/test/java/com/siemens/sw360/components/db/ComponentDatabaseHandlerTest.java
backend/src/src-components/src/test/java/com/siemens/sw360/components/db/ProjectDatabaseHandlerTest.java

Both for projects and for releases, computing the relationship tree didn't allow referencing the same project/release twice anywhere in the relationship tree even when that didn't introduce cycles.

fix broken project hierarchy and release hierarchy

---

backend/src-common/src/main/java/com/siemens/sw360/datahandler/db/ComponentDatabaseHandler.java
backend/src-common/src/main/java/com/siemens/sw360/datahandler/db/ProjectDatabaseHandler.java
backend/src/src-components/src/main/java/com/siemens/sw360/components/ComponentHandler.java
backend/src/src-projects/src/main/java/com/siemens/sw360/projects/ProjectHandler.java
frontend/sw360-portlet/src/main/java/com/siemens/sw360/portal/portlets/projects/ProjectPortlet.java
libraries/lib-datahandler/src/main/thrift/components.thrift
libraries/lib-datahandler/src/main/thrift/projects.thrift

moved computing release clearing state summaries to `ProjectDatabaseHandler` and made `ProjectPortlet` compute in bulk for all projects to save the roundtrips to backend and to the DB
closes #263

Improved Performance Of ProjectPortlet's List View

---

backend/src-common/src/main/java/com/siemens/sw360/datahandler/db/ComponentDatabaseHandler.java
backend/src-common/src/main/java/com/siemens/sw360/datahandler/db/CountingStack.java
backend/src-common/src/main/java/com/siemens/sw360/datahandler/db/ProjectDatabaseHandler.java
backend/src/src-components/src/test/java/com/siemens/sw360/components/db/ComponentDatabaseHandlerTest.java
backend/src/src-components/src/test/java/com/siemens/sw360/components/db/ProjectDatabaseHandlerTest.java
frontend/sw360-portlet/src/main/webapp/html/projects/includes/linkedProjects.jspf
frontend/sw360-portlet/src/main/webapp/html/utils/includes/linkedReleaseDetails.jspf
libraries/lib-datahandler/src/main/thrift/components.thrift
libraries/lib-datahandler/src/main/thrift/projects.thrift

fix: linked projects and linked releases tree-tables expand wrong node when the same project or release is present elsewhere in the table.
For tree-table expanding/collapsing to work correctly, values of `data-tt-id` attribute must be unique within the table. Previously, every project or release could only occur once in the table and couchdb ids were used for `data-tt-id`, but PR #264 allowed the same object to be included multiple times in the table, which broke the expanding/collapsing functionality as `data-tt-id`s were not unique anymore.

fix: linked projects and linked releases tree-tables expand wrong node

---

backend/src/src-schedule/src/main/java/com/bosch/osmi/sw360/schedule/service/ScheduleHandler.java
backend/src/src-schedule/src/main/java/com/bosch/osmi/sw360/schedule/service/ScheduleServlet.java
backend/src/src-schedule/src/main/java/com/bosch/osmi/sw360/schedule/timer/ScheduleConstants.java
backend/src/src-schedule/src/main/java/com/bosch/osmi/sw360/schedule/timer/Scheduler.java
backend/src/src-schedule/src/main/resources/sw360.properties
frontend/sw360-portlet/src/main/java/com/siemens/sw360/portal/common/PortalConstants.java
frontend/sw360-portlet/src/main/java/com/siemens/sw360/portal/portlets/admin/ScheduleAdminPortlet.java
frontend/sw360-portlet/src/main/webapp/html/admin/scheduleAdmin/view.jsp
frontend/sw360-theme/src/main/webapp/css/navigation.css
libraries/lib-datahandler/src/main/java/com/siemens/sw360/datahandler/common/CommonUtils.java
libraries/lib-datahandler/src/main/thrift/schedule.thrift
libraries/lib-datahandler/src/main/thrift/sw360.thrift
libraries/lib-datahandler/src/test/java/com/siemens/sw360/datahandler/common/CommonUtilsTest.java

This PR adds the functionality missed in the previous PR about cve search functionality.
* buttons enabled/disabled depending on whether or not cvesearch is scheduled
* offset, interval and nextScheduledSync displayed as settings
autostart scheduling
* after deployment, the scheduling service schedules all services that are registered in
the autostart property in the sw360.properties file
* if property file or one of the properties (offset, interval) is not present use default value
* if one of the properties is invalid, log this and do not schedule service
* default: cvesearch service is _not_ auto-scheduled

scheduleAdminPortlet display improved

---

backend/src-common/src/main/java/com/siemens/sw360/datahandler/db/ComponentDatabaseHandler.java
backend/src-common/src/main/java/com/siemens/sw360/datahandler/db/ProjectDatabaseHandler.java
backend/src-common/src/main/java/com/siemens/sw360/datahandler/db/ProjectRepository.java
backend/src-common/src/main/java/com/siemens/sw360/datahandler/db/ReleaseRepository.java
backend/src/src-bdpimport/src/main/java/com/bosch/osmi/sw360/bdp/datasink/thrift/ThriftExchange.java
backend/src/src-bdpimport/src/main/java/com/bosch/osmi/sw360/bdp/datasink/thrift/ThriftUploader.java
backend/src/src-bdpimport/src/main/java/com/bosch/osmi/sw360/bdp/entitytranslation/BdpComponentToSw360ReleaseTranslator.java
backend/src/src-components/src/main/java/com/siemens/sw360/components/ComponentHandler.java
backend/src/src-components/src/test/java/com/siemens/sw360/components/ComponentHandlerTest.java
backend/src/src-components/src/test/java/com/siemens/sw360/components/db/ComponentDatabaseHandlerTest.java
backend/src/src-projects/src/main/java/com/siemens/sw360/projects/ProjectHandler.java
backend/src/src-projects/src/test/java/com/siemens/sw360/projects/ProjectHandlerTest.java
frontend/sw360-portlet/src/main/java/com/siemens/sw360/portal/common/ErrorMessages.java
frontend/sw360-portlet/src/main/java/com/siemens/sw360/portal/common/PortletUtils.java
frontend/sw360-portlet/src/main/java/com/siemens/sw360/portal/portlets/AttachmentAwarePortlet.java
frontend/sw360-portlet/src/main/java/com/siemens/sw360/portal/portlets/Sw360Portlet.java
frontend/sw360-portlet/src/main/java/com/siemens/sw360/portal/portlets/components/ComponentPortlet.java
frontend/sw360-portlet/src/main/java/com/siemens/sw360/portal/portlets/projects/ProjectPortlet.java
frontend/sw360-portlet/src/main/webapp/html/components/includes/releases/editReleaseInformation.jspf
frontend/sw360-portlet/src/main/webapp/html/projects/edit.jsp
libraries/lib-datahandler/src/main/java/com/siemens/sw360/datahandler/thrift/ThriftValidate.java
libraries/lib-datahandler/src/main/thrift/components.thrift
libraries/lib-datahandler/src/main/thrift/projects.thrift
libraries/lib-datahandler/src/main/thrift/sw360.thrift

check in backend and display error in frontend in the cases when a user tries to:
* add a project with name and version equal to an existing project
* add a component with name equal to an existing component
* add a release with name and version equal to an existing release
* closes #203

avoiding duplicate documents

---

backend/src/src-cvesearch/src/main/java/org/eclipse/sw360/cvesearch/service/CveSearchHandler.java
backend/src/src-cvesearch/src/test/java/org/eclipse/sw360/cvesearch/datasource/CveSearchApiImplTest.java
backend/src/src-cvesearch/src/test/java/org/eclipse/sw360/cvesearch/datasource/CveSearchDataTestHelper.java
backend/src/src-cvesearch/src/test/java/org/eclipse/sw360/cvesearch/datasource/CveSearchGuesserTest.java
backend/src/src-cvesearch/src/test/java/org/eclipse/sw360/cvesearch/datasource/CveSearchWrapperTest.java
backend/src/src-cvesearch/src/test/java/org/eclipse/sw360/cvesearch/entitytranslation/CveSearchDataTranslatorTest.java

I couldn't find a way to make the tests actually work. No combination of options seemed to work in my environment. So I added JUnit's Assume assumptions to the failing tests, such that when the cvesearch host is not reachable, the test is ignored instead of failing.
Needs to be tested in an environment where a cvesearch host is actually available to make sure the tests aren't ignored there.
closes #279

stop CveSearch tests from failing behind proxy

---

backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/LicenseHandler.java
backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/db/LicenseDatabaseHandler.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/admin/DatabaseSanitation.java
frontend/sw360-portlet/src/main/webapp/html/admin/databaseSanitation/view.jsp
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/CommonUtils.java
libraries/lib-datahandler/src/main/thrift/licenses.thrift

This PR adds functionality to the admin portlet that all licenses and related datastructures can be removed from the database. This is helpful if someone wants to do a complete reimport of all licenses with risks, todos etc and don't want to have conflicts with already existing entries in the db. E.g. if a new version of externally packaged license information in a lics archive is to be imported into the database this feature can be useful.

License Entries removal feature at Admin portal

---

libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/CouchDbConnectorWithSecurity/CouchDbConnectorWithSecurity.java
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/CouchDbConnectorWithSecurity/Security.java
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/CouchDbConnectorWithSecurity/SecurityGroup.java
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/CouchDbConnectorWithSecurity/Status.java
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/DatabaseConnector.java

Allows credentials based connections via ektorp layer.
most of the code is taken from the Ektorp project
- i.e. see https://github.com/helun/Ektorp/commit/1b534a99c689661e81aa497ba4f05e143eca8e04

support couchdb scurity settings for restricting view access

---

backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
backend/src/src-components/src/test/java/org/eclipse/sw360/components/db/ComponentDatabaseHandlerTest.java
backend/src/src-components/src/test/java/org/eclipse/sw360/components/db/ProjectDatabaseHandlerTest.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortletUtils.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/OutTag.java
frontend/sw360-portlet/src/main/webapp/html/projects/includes/linkedProjects.jspf
frontend/sw360-portlet/src/main/webapp/html/projects/includes/projects/basicInfo.jspf
frontend/sw360-portlet/src/main/webapp/html/projects/includes/projects/summary.jspf
frontend/sw360-portlet/src/main/webapp/html/projects/licenseInfo.jsp
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/ThriftEnumUtils.java
libraries/lib-datahandler/src/main/thrift/components.thrift
libraries/lib-datahandler/src/main/thrift/projects.thrift

- on both pages, added columns for Clearing State and Type of project or release's component
- added field Clearing State to projects, displayed on both pages and in project details. editable manually
- sorted children of each node in the tree by names
- on both pages, abbreviated displayed names of releases and projects in the treetable at max 50 chars. full names displayed in a tooltip when necessary
closes #287

Improvements At Linked Projects And LicenseInfo Generation

---

backend/src/src-fossology/src/main/resources/scripts/uploadFromSW360

previously the jobs were not scheduled due to missing permissions. If the user sw360 schedules the jobs in the name of the target group, everything works well
This is sadly not related to #178

Fix permission problem in `uploadFromSW360` script

---

backend/src/src-cvesearch/src/main/java/org/eclipse/sw360/cvesearch/datasource/heuristics/SearchLevels.java
backend/src/src-cvesearch/src/main/java/org/eclipse/sw360/cvesearch/datasource/matcher/ModifiedLevenshteinDistance.java
backend/src/src-cvesearch/src/test/java/org/eclipse/sw360/cvesearch/datasource/matcher/ModifiedLevenshteinDistanceTest.java

The levenstein distance metric which is used to check if a cve is applicable to a component release, is improved in this PR. It takes now a version mismatch into account, which was not considered before.

cveSearch: only allow matches that have consumed something

---

frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/ErrorMessages.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/licenses/LicensesPortlet.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/DisplayLicensesEdit.java
frontend/sw360-portlet/src/main/webapp/html/licenses/detail.jsp
frontend/sw360-portlet/src/main/webapp/html/licenses/edit.jsp
frontend/sw360-portlet/src/main/webapp/html/utils/includes/logError.jspf

* if license links are broken, they are still displayed, but on click
error message is displayed in LicensePortlet
* edit view of LicensePortlet displays error messages if error occurs in backend
* in edit view of release: if license is not available, id is still displayed and selected in searchLicense-popup
* closes https://github.com/bsinno/sw360/issues/279

Improved License Portlet error handling

---

backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ModerationDatabaseHandler.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/homepage/MyTaskAssignmentsPortlet.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/homepage/MyTaskSubmissionsPortlet.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/moderation/ModerationPortlet.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/moderation/ModerationPortletUtils.java
frontend/sw360-portlet/src/main/webapp/css/sw360.css
frontend/sw360-portlet/src/main/webapp/html/components/view.jsp
frontend/sw360-portlet/src/main/webapp/html/moderation/view.jsp
frontend/sw360-portlet/src/main/webapp/html/projects/view.jsp

To improve handling of closed moderation requests and reduce clutter in the Moderation table, the table is split into two tables in separate tabs: one for open moderation requests (NEW and PENDING) and one for closed (APPROVED and REJECTED) ones. Also, Clearing Admins and Admins get the possibility to delete closed moderation requests via a button in the Actions column.
closes #313

Handling Closed Moderation Requests

---

scripts/migrations/004_move_release_ecc_fields_to_release_information.py

For the moderation requests the release additions and deletions were
changes due to move of ecc fields from clearing information to ecc
information.
script created with @alex-evo tested on two instances (one affecting and one empty)

fix(migration): improving ECC coverage of moderation requests

---

backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
backend/src/src-components/src/test/java/org/eclipse/sw360/components/db/ComponentDatabaseHandlerTest.java
backend/src/src-components/src/test/java/org/eclipse/sw360/components/db/ProjectDatabaseHandlerTest.java
backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/LicenseInfoGenerator.java
backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/OutputGenerator.java
backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/XhtmlGenerator.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/links/DisplayLinkToRelease.java
frontend/sw360-portlet/src/main/webapp/WEB-INF/customTags.tld
frontend/sw360-portlet/src/main/webapp/html/projects/includes/linkedProjects.jspf
frontend/sw360-portlet/src/main/webapp/html/projects/includes/projects/clearingStatus.jspf
frontend/sw360-portlet/src/main/webapp/html/utils/includes/linkedReleaseDetails.jspf
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java
libraries/lib-datahandler/src/main/thrift/components.thrift

Views unified: project/clearing status, project/linked release hierarchy, project/linked releases and projects, generated text license info file, generated xhtml license info file.
Combined columns at the first three views mentioned above to display the sort key of a release (==fullname=="vendor name version") in a single column.
Also sorted licenses in generated license info files by license names.
closes #294

unified sorting of releases in different views and license info files

---

frontend/sw360-portlet/pom.xml
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortletUtils.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java

- fixed broken linked projects and linked releases of a duplicated project. 
- reset clearing state of a duplicated project to OPEN.
- fixed a minor Maven warning.
closes #356 
closes #357

Issues With Project Duplication

---

backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/LicenseInfoHandler.java
backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/XhtmlGenerator.java
backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/parsers/AbstractCLIParser.java
backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/parsers/CLIParser.java
backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/parsers/CombinedCLIParser.java
backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/parsers/LicenseInfoParser.java
backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/parsers/SPDXParser.java
backend/src/src-licenseinfo/src/test/java/org/eclipse/sw360/licenseinfo/parsers/CLIParserTest.java
backend/src/src-licenseinfo/src/test/java/org/eclipse/sw360/licenseinfo/parsers/CombinedCLIParserTest.java
backend/src/src-licenseinfo/src/test/java/org/eclipse/sw360/licenseinfo/parsers/SPDXParserTest.java
backend/src/src-licenseinfo/src/test/resources/CombinedCLITest.xml
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/permissions/ProjectPermissions.java

- added a parser for CombinedCLI files
- also added unescaping of license texts, copyrights, and acknowledgements to work around the improperly escaped data, where the texts are stored in CDATA sections, yet are escaped.
Combined CLI parser needs a property `combined.cli.parser.external.id.correlation.key` in sw360.properties to work. The property value is the key in `release.externalIds`, by which the parser can find the release given an external Id as a reference.

LicenseInfo Parser for Combined CLI Files

---

backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ModerationDatabaseHandler.java
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/permissions/DocumentPermissions.java
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/permissions/ProjectPermissions.java
libraries/lib-datahandler/src/test/java/org/eclipse/sw360/datahandler/permissions/ProjectPermissionsTest.java
libraries/lib-datahandler/src/test/java/org/eclipse/sw360/datahandler/permissions/jgivens/GivenProject.java

No user, whether creator, contributor or moderator, is allowed to edit projects in Clearing State CLOSED. Only Clearing Admins and higher can change such projects without triggering a moderation request
closes #323

Lock projects with clearing state CLOSED for editing

---

backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
backend/src/src-components/src/test/java/org/eclipse/sw360/components/db/ComponentDatabaseHandlerTest.java

fix(releases): stop creating a release moderation request to ECC_ADMINs when a release has some ECC fields already set

Fix the check for changes in ECC fields of a release

---

backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/parsers/SPDXParser.java
backend/src/src-licenseinfo/src/test/java/org/eclipse/sw360/licenseinfo/parsers/SPDXParserTest.java

The generated reports does not include all license information due to a merge failure.

fix(spdx): `getAllLicenseTexts` was not called due to merge failure

---

frontend/sw360-portlet/src/main/webapp/html/projects/edit.jsp

This adds an additional pair of buttons to the end of the edit page.

ui(projectedit): add buttons also to bottom of edit page

---

scripts/migrations/dockerized-migration-runner.Dockerfile
scripts/migrations/dockerized-migration-runner.sh

This PR adds a tiny Dockerfile together with a script which allows the usage of the migration scripts within an isolated environment. The container uses `--net=host` to access the couchdb running on the host.
--
call as:
```
./dockerized-migration-runner.sh migrationScript [migrationScript [...]]
```
e.g.:
```
./dockerized-migration-runner.sh 003_rename_release_contacts_to_contributors.py 004_move_release_ecc_fields_to_release_information.py
```

chore(db migration): add dockerized script

---

scripts/migrations/README.md

This discribes how to use the migration scripts and documents which of them are necessary for specific upgrades.

doc(migration): add migration readme

---

libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ComponentExporter.java
libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ExcelExporter.java
libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ProjectExporter.java
libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ReleaseExporter.java

Column headers in project spreadsheet export and component spreadsheet export are prepended by `release: ` when the export is extended by releases and a release header would otherwise create a duplicate column header
closes #354

Add prefixes to duplicate column headers in spreadsheet exports

---

frontend/sw360-portlet/src/main/webapp/WEB-INF/tags/TrimLineBreaks.tag
frontend/sw360-portlet/src/main/webapp/html/components/includes/components/vulnerabilities.jspf
frontend/sw360-portlet/src/main/webapp/html/components/includes/releases/vulnerabilities.jspf
frontend/sw360-portlet/src/main/webapp/html/components/view.jsp
frontend/sw360-portlet/src/main/webapp/html/projects/includes/projects/vulnerabilities.jspf

Remove backticks from JS code to eliminate Liferay's minifier errors

Remove backticks from JS code to eliminate Liferay's minifier errors

---

libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java

make lists and maps in spreadsheet export machine-readable by exporting as JSON
closes #353

feat(export): make lists and maps in spreadsheet export machine-readable

---

README.md
backend/svc/pom.xml
pom.xml

using the following command, one is able to deploy
- the frontend via liferay and its hot deploy mechanisms
- the backend via tomcats native hot deploy mechanisms
```
$ mvn install -P deploy \
-Ddeploy.dir=/ABSOLUTE/PATH/TO/deploy/ \
-Dwebapps.dir=/ABSOLUTE/PATH/TO/webapps/
```
it is still possible to deploy everythin via the liferay deploy
mechanism using
```
$ mvn install -P deploy \
-Ddeploy.dir=/ABSOLUTE/PATH/TO/deploy/
```
to use relative paths one has to use something like:
```
$ mvn install -P deploy \
-Ddeploy.dir=$(realpath PATH/TO/deploy/) \
-Dwebapps.dir=$(realpath PATH/TO/webapps/)
```

chore(mvn): Allow to deploy backend via webapps, i.e. the tomcat hot deploy mechanism

---

backend/src/src-licenseinfo/pom.xml
backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/parsers/AbstractCLIParser.java
backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/parsers/LicenseInfoParser.java
backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/parsers/SPDXParser.java
backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/parsers/SPDXParserTools.java
backend/src/src-licenseinfo/src/test/java/org/eclipse/sw360/licenseinfo/parsers/LicenseInfoParserTest.java
backend/src/src-licenseinfo/src/test/java/org/eclipse/sw360/licenseinfo/parsers/SPDXParserTest.java
backend/src/src-licenseinfo/src/test/resources/SPDXRdfExample-v1.1.rdf
backend/src/src-licenseinfo/src/test/resources/SPDXRdfExample-v1.2.rdf

This pull request fixes a problem in the SPDX parsing and also refactors the SPDX-parser. This is done in preparation for adding support for TagValue-SPDX files. Sadly there is a bug in the current implementation of spdx-tools, which stop the code from working. It will be contributed as soon as it works.
In addition are tests added, which check whether the old SPDX-formats (1.1 and 1.2) can be parsed.
This PR adds a new dependency: com.tngtech.java.junit-dataprovider, which simplifies the implementation of parametrized tests. It is under Apache2

fix(licenseinfo): currently copyrights in SPDX files are not parsed correctly

---

backend/src/src-cvesearch/src/main/java/org/eclipse/sw360/cvesearch/datasource/CveSearchWrapper.java
backend/src/src-cvesearch/src/main/java/org/eclipse/sw360/cvesearch/datasource/heuristics/SearchLevels.java
backend/src/src-cvesearch/src/test/java/org/eclipse/sw360/cvesearch/datasource/heuristics/SearchLevelsTest.java

a new formatted cpe is: `cpe:2.3:a:Vendor:Product:Version`
an old formatted cpe is: `cpe:/a:vendor:product:version:~~~~` 
and cleanup code: remove unused heuristics

feat(cve-search): convert old cpe format on demand

---

backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/db/LicenseDatabaseHandler.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/licenses/LicensesPortlet.java
frontend/sw360-portlet/src/main/webapp/html/licenses/includes/detailSummary.jspf
frontend/sw360-portlet/src/main/webapp/html/licenses/includes/editDetailSummary.jspf
libraries/commonIO/src/main/java/org/eclipse/sw360/commonIO/ConvertRecord.java
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/ThriftEnumUtils.java
libraries/lib-datahandler/src/main/thrift/licenses.thrift
libraries/lib-datahandler/src/main/thrift/projects.thrift
libraries/lib-datahandler/src/main/thrift/schedule.thrift
libraries/lib-datahandler/src/main/thrift/sw360.thrift
scripts/migrations/005_convert_compatibility_fields_to_ternary.py
scripts/migrations/README.md

This PR replaces the types of two fileds `GPLv2Compatibility` and `GPLv3Compatibility` with a ternary value. This allows to express `"YES"`, `"NO"` and `"UNKNOWN"`.
The corresponding migration script maps the old values in the following way:
- `True` becomes `YES`
- `No` becomes `UNKNOWN`

Replace compatibility bool with ternary value

---

backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ReleaseRepository.java
backend/src/src-components/src/main/java/org/eclipse/sw360/components/ComponentHandler.java
backend/src/src-components/src/test/java/org/eclipse/sw360/components/db/ComponentDatabaseHandlerTest.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
libraries/lib-datahandler/src/main/thrift/components.thrift

- fix(releases): fix too strict duplicate check for releases that matches prefixes of existing release names
- rename confusingly named method in thrift api to match its function
closes #317

fix(releases): fix too strict duplicate check for releases

---

scripts/migrations/repair_missing_sha1_hashes.py

Add a script to repair missing attachment sha1 hashes. This is not necessary for running sw360portal, but may be necessary for other reasons

chore(db): add script to repair missing attachment sha1 hashes

---

.travis.yml
scripts/install-thrift.sh

This adds a test which checks whether
- all specified dependencies are used and
- all used dependencies are explicitly specified.
This test is currently allowed to fail, I hope we will be able to change this soon.
This also adds a test which just runs `mvn verify` to fail early if the poms are invalid.

chore(travis): add test which checks the maven dependency situation

---

backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/UserRepository.java
backend/src/src-users/src/main/java/org/eclipse/sw360/users/db/UserDatabaseHandler.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/DisplayUserEmailCollection.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/DisplayUserGroup.java
frontend/sw360-portlet/src/main/webapp/WEB-INF/customTags.tld
frontend/sw360-portlet/src/main/webapp/html/components/includes/components/vulnerabilities.jspf
frontend/sw360-portlet/src/main/webapp/html/ecc/view.jsp
frontend/sw360-portlet/src/main/webapp/html/moderation/view.jsp
frontend/sw360-portlet/src/main/webapp/html/projects/ajax/searchProjectsAjax.jsp
frontend/sw360-portlet/src/main/webapp/html/projects/includes/attachmentSelectTable.jspf
frontend/sw360-portlet/src/main/webapp/html/utils/includes/usingProjectsTable.jspf
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/DatabaseConnector.java
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/DatabaseRepository.java
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/thrift/ThriftValidate.java
libraries/lib-datahandler/src/main/thrift/components.thrift

- skip looking up real names where many roundtrips are expected
- drop usage of DisplayUserGroup for ECC overview and preload creators' departments to releases instead

chore(performance): improve page loading by skipping DB lookups of users

---

.travis.yml

The pull request https://github.com/sw360/sw360portal/pull/415 has modified the travis configuration to run multiple tests (see https://travis-ci.org/sw360/sw360portal/builds/236344373). But currently only two of them (`validate` and `dependency:analyze`) are called.
This PR should fix that.

fix(travis): add missing test explicitly to matrix

---

backend/src-common/src/main/java/org/eclipse/sw360/components/summary/ProjectSummary.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
backend/src-common/src/test/java/org/eclipse/sw360/components/summary/ProjectSummaryTest.java
backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ProjectModerationRequestGenerator.java
backend/src/src-projects/src/main/java/org/eclipse/sw360/projects/ProjectHandler.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/DisplayProjectChanges.java
libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ComponentExporter.java
libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ComponentHelper.java
libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ExcelExporter.java
libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ExporterHelper.java
libraries/exporters/src/main/java/org/eclipse/sw360/exporter/LicenseExporter.java
libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ProjectExporter.java
libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ProjectHelper.java
libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ReleaseExporter.java
libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ReleaseHelper.java
libraries/exporters/src/main/java/org/eclipse/sw360/exporter/VendorExporter.java
libraries/exporters/src/test/java/org/eclipse/sw360/exporter/ProjectExporterTest.java
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/thrift/ThriftValidate.java
libraries/lib-datahandler/src/main/thrift/projects.thrift

- use streaming poi api to improve performance of spreadsheet export with many documents
- preload related data in ExcelExporters to reduce roundtrips to DB
- enable simultaneous parallel exports (they were mangled by usage of static fields)
- delete unused field Project.releaseIds
closes #422

fix(export): improve performance of spreadsheet export and fix simultaneous exports

---

libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/CommonUtils.java

CommonUtils.loadResource returns an `Optional` with empty byte array when the resourceFilePath is an empty string, because the resulting filename to be read happens to be the `/etc/sw360` folder). Instead, it should return an empty `Optional`.

fix(utils): handle empty resourceFilePath in CommonUtils.loadResource()

---

backend/pom.xml
backend/src/src-attachments/pom.xml
backend/src/src-cvesearch/pom.xml
backend/src/src-fossology/pom.xml
backend/src/src-licenseinfo/pom.xml
backend/utils/pom.xml
frontend/sw360-portlet/pom.xml
frontend/sw360-portlet/src/test/java/org/eclipse/sw360/portal/portlets/projects/ProjectImportPortletTest.java
libraries/exporters/pom.xml
libraries/lib-datahandler/pom.xml
pom.xml

In this commit not all dependencies were forced to their latest state. The changes are listed in the following table
| dependency | old version | new version | latest version |
| --- | --- | --- | --- |
| ch.qos.logback:logback-classic | 1.1.2 | 1.2.3 | |
| ch.qos.logback:logback-core | 1.1.2 | 1.2.3 | |
| com.google.code.gson:gson | 2.6.2 | 2.8.0 | |
| com.google.guava:guava | 18.0 | 21.0 | 22.0-android |
| com.jcraft:jsch | 0.1.51 | 0.1.54 | |
| com.liferay.portal:portal-service | 6.2.1 | 6.2.2 | 6.2.5 |
| com.liferay.portal:util-bridges | 6.2.1 | 6.2.2 | 6.2.5 |
| com.liferay.portal:util-java | 6.2.1 | 6.2.2 | 6.2.5 |
| com.liferay.portal:util-taglib | 6.2.1 | 6.2.2 | 6.2.5 |
| commons-cli:commons-cli | 1.2 | 1.4 | |
| com.tngtech.java:junit-dataprovider | 1.10.0 | 1.12.0 | |
| …

chore(mvn): update dependency versions in poms

---

scripts/migrations/dockerized-migration-runner.Dockerfile
scripts/migrations/dockerized-migration-runner.sh

Currently the migration scripts are hard-wired into the docker image related to the dockerized-migration-runner. This changes it to mount the folder with all the scripts as volume.
Now, one does not have to recreate the docker image, if the scripts have changed.

fix(migrations): do not add scripts to docker image

---

frontend/sw360-portlet/src/main/webapp/html/admin/databaseSanitation/view.jsp
frontend/sw360-portlet/src/main/webapp/html/projects/import.jsp

This PR replaces some raw `$.ajax(...)` calls by  `$.confirm({content: function () {return $.ajax({...});}})`, which also handles the spinner thing and block the UI (by overlaying it).
The Spinners were added at:
- Database sanitation: while removing all licenses and while importing spdx licenses
- projectimport: which testing Auth, while loading projects and while importing
Screenshot:

feat(ui): add spinners at long running requests

---

backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
backend/src/src-components/src/main/java/org/eclipse/sw360/components/ComponentHandler.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/FossologyAwarePortlet.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ComponentExporter.java
libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ComponentHelper.java
libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ProjectExporter.java
libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ProjectHelper.java
libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ReleaseExporter.java
libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ReleaseHelper.java
libraries/lib-datahandler/src/main/thrift/components.thrift

* added project origin string from gui to export which means that after three project names only "..." will be printed if there are more
* added component type to exported data and therefore added db query for component info for each release (=export row)
* fixed changing releases because of unset attachments - this broke the HashMap keys in releaseStringMap (changing key objects is evil)
* removed unused loggers
fixes #425

feat(clearing export): add project origin and component type to exported data

---

frontend/sw360-portlet/src/main/webapp/html/utils/includes/searchReleasesFromRelease.jsp

Stops current release from being selected from the table of possible releases,
this closes #444

fix(ui): preventing release from linking to itself

---

backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
backend/src/src-components/src/test/java/org/eclipse/sw360/components/db/ComponentDatabaseHandlerTest.java
backend/src/src-vendors/src/main/java/org/eclipse/sw360/vendors/VendorHandler.java
libraries/importers/component-importer/src/main/java/org/eclipse/sw360/importer/ComponentImportUtils.java

Showing vendor short name rather than vendor long name in component listings by changing the content of the vendorNames field,
closes #355

fix(ui): Changing content of vendorNames to be vendor short names

---

frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/DisplayEllipsisString.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/DisplayEnumShort.java
frontend/sw360-portlet/src/main/webapp/WEB-INF/customTags.tld
frontend/sw360-portlet/src/main/webapp/css/sw360.css
frontend/sw360-portlet/src/main/webapp/html/utils/includes/attachmentsDetail.jsp
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/ThriftEnumUtils.java

* removed old attachmentsDetail.jsp code including its css in sw360.css
* added new attachment list view based on jquery datatable plugin with child rows
** added data generation as writing javascript array into the html via jsp
** added js code to generate table from data and dynamically add child rows for details
** added css partly to jsp (different size adjustments) and mainly to sw360.css
** added two new tags for type shortnames and too long text with ellipses
** added idea of shortnames for enum types to ThriftEnumUtils
* not yet done - needs further ticket:
** size and usage data, just n/a is printed in table cell
** edit and delete actions
closes #454

refactor(attachments list): new look of list view for attachments

---

frontend/sw360-portlet/src/main/webapp/html/utils/includes/usingProjectsTable.jspf

Creates the table using the DataTables plugin, so it can be sorted by clicking on the headers. 
This fixes issue #453

fix(ui): adding sort functionality to usingProjects table

---

frontend/sw360-portlet/src/main/webapp/html/utils/ajax/linkedReleasesAjax.jsp
frontend/sw360-portlet/src/main/webapp/html/utils/includes/linkedReleaseDelete.jspf

- Add the release name and version (also vendor) to the confirmation message in case of deletion the release link from a project.
- fix issue #442

chore(ui): add release name and version in remove link confirmation

---

frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
frontend/sw360-portlet/src/main/webapp/html/projects/view.jsp
libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ComponentExporter.java
libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ComponentHelper.java
libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ProjectExporter.java
libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ProjectHelper.java
libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ReleaseExporter.java
libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ReleaseHelper.java

* added component type to every row that ReleaseHelper creates
* therefore has to batch load parent components of releases in more cases
* has been part of additional data only for clearing status exports
* now this additional data is only the project origin
closes sw360/sw360portal#326

feat(exports): add component type to release row in spreadsheet exports

---

frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
frontend/sw360-portlet/src/main/resources/org/eclipse/sw360/portal/mapper/component-friendly-url-routes.xml
frontend/sw360-portlet/src/main/resources/org/eclipse/sw360/portal/mapper/license-friendly-url-routes.xml
frontend/sw360-portlet/src/main/resources/org/eclipse/sw360/portal/mapper/moderation-friendly-url-routes.xml
frontend/sw360-portlet/src/main/resources/org/eclipse/sw360/portal/mapper/project-friendly-url-routes.xml
frontend/sw360-portlet/src/main/resources/org/eclipse/sw360/portal/mapper/search-friendly-url-routes.xml
frontend/sw360-portlet/src/main/resources/org/eclipse/sw360/portal/mapper/vulnerability-friendly-url-routes.xml
frontend/sw360-portlet/src/main/webapp/WEB-INF/liferay-portlet.xml
frontend/sw360-portlet/src/main/webapp/html/components/view.jsp
frontend/sw360-portlet/src/main/webapp/html/projects/view.jsp

Activated liferay friendly mapper functionality for the following portlets:
- projects
- components (releases included)
- licenses
- moderations
- vulnerabilities
- search
The structure for all friendly links is:
https://localhost:8443/group/guest/{portlet]/-/{porlet}/{page}/{id}
feat(ui): provide friendly URLs in liferay
Closes sw360/sw360portal#28

feat(ui): provide friendly URLs in liferay

---

backend/src-common/src/main/java/org/eclipse/sw360/components/summary/ModerationRequestSummary.java
backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ModerationDatabaseHandler.java
frontend/sw360-portlet/src/main/webapp/html/moderation/components/delete.jsp
frontend/sw360-portlet/src/main/webapp/html/moderation/components/merge.jsp
frontend/sw360-portlet/src/main/webapp/html/moderation/projects/merge.jsp
frontend/sw360-portlet/src/main/webapp/html/moderation/releases/delete.jsp
frontend/sw360-portlet/src/main/webapp/html/moderation/releases/merge.jsp
frontend/sw360-portlet/src/main/webapp/html/moderation/view.jsp
libraries/lib-datahandler/src/main/thrift/moderation.thrift
scripts/migrations/008_add_component_type_to_moderation_requests.py
scripts/migrations/README.md

- Added `ComponentType` to `moderation.thrift`
- For components and releases this is automatically set. For releases the type of the parent component is chosen. For other moderation requests (e.g. for projects) this field is not set.
- The moderation request listing now contains an additional column displaying the component type.
Closes sw360/sw360portal#459

feat(ui): Added component type to the listing of moderation requests

---

frontend/sw360-portlet/src/main/webapp/html/components/view.jsp

The counter number is decremented by 1 and then counter text is set with the new number. This fixes issue #467

fix(ui): Component counter updates automatically after deletion

---

frontend/sw360-portlet/src/main/webapp/html/projects/ajax/linkedProjectsAjax.jsp
frontend/sw360-portlet/src/main/webapp/html/projects/includes/searchProjects.jsp
frontend/sw360-portlet/src/main/webapp/html/utils/ajax/linkedReleasesAjax.jsp
frontend/sw360-portlet/src/main/webapp/html/utils/ajax/linkedReleasesRelationAjax.jsp
frontend/sw360-portlet/src/main/webapp/html/utils/includes/searchReleases.jsp

* For linking releases and projects to projects changed the id for the rows in the Linked Releases and Projects-Table in the project edit view.
* At the same time also fixed an error in the projects and releases search dialogs
Closes sw360/sw360portal#541

fix(ui): Fixed deletion of wrongly linked releases

---

frontend/sw360-portlet/src/main/webapp/html/licenses/detail.jsp
frontend/sw360-portlet/src/main/webapp/html/licenses/includes/detailTodos.jspf
frontend/sw360-portlet/src/main/webapp/html/moderation/licenses/merge.jsp

Adds a cancel button that resets checkboxes and cancels edit mode,
fixes #267

fix(bug): Adding cancel button while editing license whitelist

---

frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/ThriftEnumUtils.java
libraries/lib-datahandler/src/main/thrift/projects.thrift

Adds inner source as an option for project type when creating/editing a project
fixes #549

feat(projects): Adding inner source as an option for project type

---

libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/ThriftEnumUtils.java
libraries/lib-datahandler/src/main/thrift/attachments.thrift

Adds ReadMe OSS as an option when adding a new attachment or editing attachments
fixes #523

feat(attachments): Adding ReadMe OSS document type to attachments

---

backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ModerationRequestGenerator.java
backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ReleaseModerationRequestGenerator.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortletUtils.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortletUtils.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/TagUtils.java
frontend/sw360-portlet/src/main/webapp/html/components/editRelease.jsp
frontend/sw360-portlet/src/main/webapp/html/components/includes/releases/editExternalIds.jsp
frontend/sw360-portlet/src/main/webapp/html/utils/includes/mapEdit.jspf
frontend/sw360-portlet/src/main/webapp/js/main.js
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/Moderator.java

- Creates new editable table to represent external Ids in edit release view, which can be used to update the external ids.
- Modifies the getCustomMapFromRequest method in PortletUtils so that it can be used for external id map.
Edit: Updating branch so it is up-to-date with master
Closes sw360/sw360portal#436

feat(ui): Making external ids editable from release

---

backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxUtils.java
backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/OutputGenerator.java
backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/parsers/SPDXParserTools.java
backend/src/src-licenseinfo/src/test/java/org/eclipse/sw360/licenseinfo/parsers/SPDXParserTest.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortletUtils.java

https://github.com/sw360/sw360portal/issues/575
* License names have LicenseRef prefix in License Info Documents when using SPDX
* License Texts miss formatting in lLicense Info document when using SPDX RDF
* License Texts are present multiple times in License Info Doc if generated from spdx report

fix(bug): Some fixes in LicenseInfo DOCX generation

---

frontend/sw360-portlet/src/main/webapp/html/components/includes/vendors/searchVendor.jspf
frontend/sw360-portlet/src/main/webapp/js/components/includes/vendors/searchVendor.js

Use colgroups to make columns of both tables the same width.
It is nearly impossible to use only one table and make the tbody scrollable.
Closes sw360/sw360portal#516

fix(vendorsearch): align table headers

---

backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/AttachmentAwareDatabaseHandler.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
backend/src-common/src/test/java/org/eclipse/sw360/datahandler/db/AttachmentAwareDatabaseHandlerTest.java
frontend/sw360-portlet/src/main/webapp/html/components/edit.jsp
frontend/sw360-portlet/src/main/webapp/html/components/editRelease.jsp
frontend/sw360-portlet/src/main/webapp/html/projects/edit.jsp
frontend/sw360-portlet/src/main/webapp/html/utils/includes/editAttachments.jspf
frontend/sw360-portlet/src/main/webapp/js/modules/datatables-renderer.js
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/AttachmentConnector.java
libraries/lib-datahandler/src/test/java/org/eclipse/sw360/datahandler/couchdb/AttachmentConnectorTest.java

* Attachments can only be deleted if they are not approved (enforced this in the backend)
* In the GUI a warning is displayed if the user wants to delete an approved attachment, that does not allow him to do so.
Closes sw360/sw360portal#457

feat(attachments): Prevent deletion of approved attachments

---

.travis.yml
.travis/testForLicenseHeaders.sh
backend/src/src-cvesearch/src/main/java/org/eclipse/sw360/cvesearch/datasource/matcher/Match.java
backend/src/src-cvesearch/src/test/java/org/eclipse/sw360/cvesearch/datasource/heuristics/SearchLevelsTest.java
backend/src/src-cvesearch/src/test/java/org/eclipse/sw360/cvesearch/helper/VulnerabilityUtilsTest.java
backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/util/LicenseNameWithTextUtils.java
backend/src/src-licenseinfo/src/main/resources/velocity-tools.xml
backend/src/src-licenseinfo/src/test/java/org/eclipse/sw360/licenseinfo/util/LicenseNameWithTextUtilsTest.java
backend/src/src-licenseinfo/src/test/resources/CombinedCLITest.xml
backend/src/src-search/src/main/java/org/eclipse/sw360/search/Sw360usersDatabaseSearchHandler.java
backend/src/src-search/src/main/java/org/eclipse/sw360/search/db/Sw360dbDatabaseSearchHandler.java
backend/src/src-users/src/test/java/org/eclipse/sw360/users/UserHandlerTest.java
frontend/sw360-portlet/src/main/webapp/WEB-INF/liferay-display.xml
frontend/sw360-portlet/src/main/webapp/html/components/includes/releases/editExternalIds.jsp
frontend/sw360-portlet/src/main/webapp/html/utils/includes/logError.jspf
frontend/sw360-portlet/src/test/java/org/eclipse/sw360/portal/TestUserCacheHolder.java
frontend/sw360-portlet/src/test/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortletUtilsTest.java
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/WrappedException.java

This adds a simple script `.travis/testForLicenseHeaders.sh` which checks with a very simple heuristic whether all files contain a license header.

feat(travis): test that all files contain license headers

---

backend/src/src-licenseinfo/src/main/resources/textLicenseInfoFile.vm

tiny modification to the velocity template for plain text generation.
Removed xml-escaping.

feat(licenseinfo): clean license texts in license info generation

---

libraries/commonIO/pom.xml
libraries/commonIO/src/main/java/org/eclipse/sw360/commonIO/ConvertRecord.java
libraries/commonIO/src/test/java/org/eclipse/sw360/commonIO/ConvertRecordTest.java
libraries/lib-datahandler/src/main/thrift/licenses.thrift

also add (optional) external IDs for Licenses and TODOs (only used while importing and exporting)

feat(lics): also import and export external IDs

---

backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
backend/src-common/src/test/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandlerTest.java
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java

Duplicating a project makes a deep copy of the original, including linked projects and releases, but then for displaying project edit page, linked projects are searched in backend. SW360Utils, however, refused to search for linked projects of a project that has no id and the backend wasn't capable of returning them.
- relaxed the check of project in SW360Utils
- made ProjectDatabaseHandler capable of returning linked projects of a new project (without id yet)
- added some tests to prevent regressions
closes sw360/sw360portal#673

fix(projects): duplicating project does not copy linked projects

---

frontend/sw360-portlet/src/main/webapp/html/projects/includes/detailOverview.jspf
frontend/sw360-portlet/src/main/webapp/html/projects/includes/projects/clearingStatus.jspf
frontend/sw360-portlet/src/main/webapp/html/projects/includes/projects/eccStatus.jspf

- add new tab ECC Status to projects (same fields as in ECC listing page)
- export release spreadsheet will return the same excel sheet as from Clearing Status tab
closes sw360/sw360portal#349

feat(project): add ECC status information to projects

---

backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
backend/src/src-components/src/main/java/org/eclipse/sw360/components/ComponentHandler.java
backend/src/src-components/src/test/java/org/eclipse/sw360/components/db/ComponentDatabaseHandlerTest.java
backend/src/src-vulnerabilities/src/main/java/org/eclipse/sw360/vulnerabilities/VulnerabilityHandler.java
backend/src/src-vulnerabilities/src/main/java/org/eclipse/sw360/vulnerabilities/db/VulnerabilityDatabaseHandler.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/CommonVulnerabilityPortletUtils.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/CustomFieldHelper.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortletUtils.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortletUtils.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/vulnerabilities/VulnerabilitiesPortlet.java
frontend/sw360-portlet/src/main/webapp/html/components/includes/components/vulnerabilities.jspf
frontend/sw360-portlet/src/main/webapp/html/components/includes/releases/vulnerabilities.jspf
frontend/sw360-portlet/src/main/webapp/html/projects/includes/projects/vulnerabilities.jspf
frontend/sw360-portlet/src/main/webapp/html/utils/includes/usingReleasesTable.jspf
frontend/sw360-portlet/src/main/webapp/html/vulnerabilities/view.jsp
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/thrift/ThriftUtils.java
libraries/lib-datahandler/src/test/java/org/eclipse/sw360/datahandler/thrift/ThriftUtilsTest.java

Limit the size of the related vulnerability tables (in the UI) for project/component/release
* Allow for choose the size of tables of related vulnerabilities
* limit db requests to vulnerabilities
* limit db requests to component and releases
* Also fixes https://github.com/sw360/sw360portal/issues/657

feat(vulnerability): Limit the size of the related vulnerability tables

---

frontend/sw360-portlet/src/main/webapp/css/sw360.css
frontend/sw360-portlet/src/main/webapp/html/moderation/view.jsp

- hide horizontal and vertical scrollbar in the navigation tabs (on different zoom levels)
- resize the moderation datatable while zooming
closes sw360/sw360portal#678

fix(ui): hide scrollbar in tab menu and resize moderation table while zooming

---

backend/src/src-cvesearch/pom.xml
backend/src/src-schedule/pom.xml

There were unused liferay dependencies in the backend.
Can be merged after travis is green.

fix(pom): remove some unused dependencies

---

backend/src-common/src/main/java/org/eclipse/sw360/components/summary/ComponentSummary.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentRepository.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ReleaseRepository.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/UserRepository.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/VendorRepository.java
backend/src/src-attachments/src/main/java/org/eclipse/sw360/attachments/db/AttachmentRepository.java
backend/src/src-cvesearch/src/main/java/org/eclipse/sw360/cvesearch/datasink/VulnerabilityConnector.java
backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/db/LicenseRepository.java
backend/src/src-vendors/src/main/java/org/eclipse/sw360/vendors/VendorDatabaseHandler.java
backend/src/src-vendors/src/main/java/org/eclipse/sw360/vendors/VendorHandler.java
backend/src/src-vulnerabilities/src/main/java/org/eclipse/sw360/vulnerabilities/db/VulnerabilityDatabaseHandler.java

This PR tackles multiple issues:
1. Couchdb recommends that Views should not emit the document, i.e. instead of `emit(null, doc)` one should use `emit(null, doc._id)`. This improves performance and reduces the size of the cached views. The documents are still delivered via the `includeDocs=true` property
2. The `ComponentSummary` was inefficiently implemented. If one wanted to have a summary of Components it collected **all Releases for every component** and filtered them later to fill in the details.
- this raises the question whether Summaries should only be projections?
3. There was no `VendorDatabaseHandler` and there was much logic in the `VendorRepository`.

chore(repositories): refactor and cleanup CouchDB Repositories

---

frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortletUtils.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projectimport/ProjectImportPortlet.java
frontend/sw360-portlet/src/main/webapp/html/projects/import.jsp
frontend/sw360-portlet/src/test/java/org/eclipse/sw360/portal/portlets/projectimport/ProjectImportPortletTest.java
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/thrift/ThriftClients.java
libraries/lib-datahandler/src/main/thrift/importstatus.thrift
libraries/lib-datahandler/src/main/thrift/projectimport.thrift

Instead of a list of IDs, now a error message is shown for each failed ID with a reason for the failure.
Backend PR:  https://github.com/sw360/sw360bdpImportService/pull/5
Depends on PR: https://github.com/sw360/sw360portal/pull/661
(note that before the message was like 'there was some problem', now it shall display which projects etc)

feat(bdpImport): Use of proper error message when importing projects

---

.gitignore
backend/src/src-attachments/src/main/java/org/eclipse/sw360/attachments/AttachmentHandler.java
backend/src/src-attachments/src/test/java/org/eclipse/sw360/attachments/AttachmentHandlerTest.java
backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/LicenseInfoHandler.java
backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxUtils.java
backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/OutputGenerator.java
backend/src/src-licenseinfo/src/main/resources/textLicenseInfoFile.vm
backend/src/src-licenseinfo/src/main/resources/xhtmlLicenseInfoFile.vm
backend/src/src-licenseinfo/src/test/java/org/eclipse/sw360/licenseinfo/outputGenerators/XhtmlGeneratorTest.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
frontend/sw360-portlet/src/main/webapp/html/projects/includes/attachmentSelectTable.jspf
libraries/lib-datahandler/src/main/thrift/attachments.thrift

display error messages at license selection screen and in the generated
license info files when one of the attachments cannot be parsed, as opposed
to failing outright.
merge license info data when multiple CLI attachments were selected by
the user (only for text and xhtml generators)
closes sw360/sw360portal#606

feat(licenseinfo): make licenseinfo generation more robust

---

rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/attachment/AttachmentController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/attachment/Sw360AttachmentService.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/Sw360ComponentService.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestExceptionHandler.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/LicenseController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/Sw360LicenseService.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/integration/ComponentTest.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/integration/ProjectTest.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/integration/TestIntegrationBase.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/integration/UserTest.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/AttachmentSpecTest.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/LicenseSpecTest.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java

New optional request parameter for project controller (transitive)
e.g. 
```
without request parameter / or false:
/resource/api/projects/123456/releases
/resource/api/projects/123456/releases/ecc
/resource/api/projects/123456/releases?transitive=false
/resource/api/projects/123456/releases?transitive=false/ecc
```
```
with request parameter: transitive
/resource/api/projects/123456/releases?transitive=true
/resource/api/projects/123456/releases?transitive=true/ecc
```
closes sw360/sw360portal#733

feat(rest): list all transitive releases for a specific project

---

rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/attachment/AttachmentController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestExceptionHandler.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/serializer/JsonInstantSerializer.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/serializer/JsonProjectRelationSerializer.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/serializer/JsonReleaseRelationSerializer.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/AttachmentSpecTest.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java

- All releases for a project are now displayed
- Added `linkRelation` to the self link of linked releases
```
"containedReleases": [
{
"name": "Release ABC",
"version": "1.2.3",
"clearingState": "APPROVED",
"_links": {
"self": {
"href": "https://localhost:8443/resource/api/releases/1234567.....",
"linkRelation": {
"releaseRelation": "CONTAINED",
"mainlineState": "OPEN"
}
}
}
}
]
```
closes sw360/sw360portal#718
closes sw360/sw360portal#722

fix(rest): show all linked releases with project relationship information

---

frontend/sw360-portlet/src/main/webapp/html/components/detailRelease.jsp

- remove the bracket at the end of a component name (release summary)
closes sw360/sw360portal#752

chore(ui): remove bracket at the end of a component name

---

rest/resource-server/src/docs/asciidoc/api-guide.adoc
rest/resource-server/src/docs/asciidoc/components.adoc
rest/resource-server/src/docs/asciidoc/projects.adoc
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vulnerability/VulnerabilityController.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/UserSpecTest.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/VendorSpecTest.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/VulnerabilitySpecTest.java

Added the following chapters
Projects Chapter:
- Listing projects by name
- Listing projects by type
- Listing releases of a single projects
- Listing releases with ecc information
Components Chapter:
- Listing components by name
- Listing components by type
... and some fixes (typo, add fields, field descriptions...)

feat(rest): add search parameter name, type and transitive to documentation

---

rest/resource-server/pom.xml

- change maven phase for plugins `'generate-docs',` `'copy-resources'`
--> **prepare-package**
moved plugin `'pring-boot-maven-plugin'` to the end.
closes sw360/sw360portal#758

fix(rest): change maven plugin order to generate the documentation correctly

---

frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/DisplayCountryCodeName.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/DisplayCountryCodeSelection.java
frontend/sw360-portlet/src/main/webapp/WEB-INF/customTags.tld
frontend/sw360-portlet/src/main/webapp/html/components/includes/components/editBasicInfo.jspf
frontend/sw360-portlet/src/main/webapp/html/components/includes/components/summary.jspf
frontend/sw360-portlet/src/main/webapp/html/projects/includes/projects/basicInfo.jspf
frontend/sw360-portlet/src/main/webapp/html/projects/includes/projects/summary.jspf

- added two new tags (display name, display options)
- ISO-3166-1 / Alpha 2 Codes
- configurable preferred country code list in sw360.properties
(preferred.country.codes: DE,AT,CH,US)
closes sw360/sw360portal#750

feat(ui): improve handling of country fields

---

backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/LicenseInfoHandler.java
backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxGenerator.java
backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxUtils.java
backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/OutputGenerator.java
backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/TextGenerator.java
backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/XhtmlGenerator.java
backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/parsers/AbstractCLIParser.java
backend/src/src-licenseinfo/src/main/resources/textLicenseInfoFile.vm
backend/src/src-licenseinfo/src/main/resources/xhtmlLicenseInfoFile.vm
backend/src/src-licenseinfo/src/test/java/org/eclipse/sw360/licenseinfo/outputGenerators/XhtmlGeneratorTest.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/DisplayOutputFormats.java
libraries/lib-datahandler/src/main/thrift/licenseinfo.thrift

this PR supports to generate different output variants for the DOCX generator
- disclosure license info file
- report license info file (contains sw360 license todos)
- add project title (project name and version) to text/xhtml generator

feat(licenseinfo): Generate different variants of DOCX files

---

rest/resource-server/src/docs/asciidoc/components.adoc
rest/resource-server/src/docs/asciidoc/projects.adoc
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/HalResource.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/LicenseController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/user/UserController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vendor/VendorController.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/AttachmentSpecTest.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/LicenseSpecTest.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/UserSpecTest.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/VendorSpecTest.java

- bug fix in tests for search by name (**projects**, **components**)
- bug fix show licenses for project (e.g. _/projects/123456/licenses_)
- harmonize fields for resource objects (name, version, type)
- add fields `mainlineState`, `downloadUrl` (**release**)
- add field `createdBy` (**attachments**)
- add fields `al`, `eccn` (**eccInformation**)
closes sw360/sw360portal#760
closes sw360/sw360portal#766

chore(rest): harmonize rest fields and documentation

---

frontend/sw360-portlet/src/main/webapp/html/components/includes/releases/editReleaseInformation.jspf
scripts/migrations/009_overwrite_release_name_with_component_name.py
scripts/migrations/README.md

- changed release edit view (component name is set to release name and is not editable)
- added migration script (_009_overwrite_release_name_with_component_name.py_)
(this scripts supports `DRY_RUN` option to show the different release/component names)
closes sw360/sw360portal#451

feat(release): make release names not editable

---

libraries/lib-datahandler/src/test/java/org/eclipse/sw360/datahandler/couchdb/AttachmentContentDownloaderTest.java

- unfortunately this test fails because the blackhole ip (_192.0.2.0_) is not reachable in the network.
- this can happen in automated ci environments
```
FAILURE!
java.lang.AssertionError: 
Expected: (a string containing "timed out" or a string containing "Das Netzwerk ist nicht erreichbar")
but: was "No route to host (Host unreachable)"
```

chore(datahandler): remove assertion for couchdb test (lib-datahandler)

---

libraries/lib-datahandler/src/test/java/org/eclipse/sw360/datahandler/couchdb/AttachmentContentDownloaderTest.java

This reverts commit 3b90fe7e6dcc56f211cb3f633e275352b988e0f6 and fixes the internationalization bug.
related to #784

test(datahandler): add assertion for couchdb test (lib-datahandler)

---

backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxGenerator.java
backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/OutputGenerator.java
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/CommonUtils.java

changed velocity context configuration to load from file and class
1. **file** (/etc/sw360/)
2. **class** (./WEB-INF/classes/)
closes sw360/sw360portal#330
_edit, +template path configuration for docx generation_

feat(licenseinfo): allows velocity to load templates from etc/sw360

---

rest/authorization-server/pom.xml
rest/resource-server/pom.xml

- removed the auto build for fatjars in rest projects
--> added maven profile to obtain the option to build rest fatjars
closes sw360/sw360portal#799

fix(rest): seperate creation of rest fatjars to maven profile

---

backend/src-common/src/main/java/org/eclipse/sw360/components/summary/ProjectSummary.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectRepository.java
backend/src/src-projects/src/main/java/org/eclipse/sw360/projects/ProjectHandler.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
frontend/sw360-portlet/src/main/webapp/html/components/detail.jsp
frontend/sw360-portlet/src/main/webapp/html/components/detailRelease.jsp
frontend/sw360-portlet/src/main/webapp/html/components/edit.jsp
frontend/sw360-portlet/src/main/webapp/html/moderation/components/merge.jsp
frontend/sw360-portlet/src/main/webapp/html/moderation/projects/merge.jsp
frontend/sw360-portlet/src/main/webapp/html/moderation/releases/merge.jsp
frontend/sw360-portlet/src/main/webapp/html/projects/detail.jsp
frontend/sw360-portlet/src/main/webapp/html/projects/edit.jsp
frontend/sw360-portlet/src/main/webapp/html/utils/includes/usingComponentsTable.jspf
frontend/sw360-portlet/src/main/webapp/html/utils/includes/usingProjectsTable.jspf
libraries/lib-datahandler/src/main/thrift/projects.thrift

- hide inaccessible projects in the "is used by the following" section for a component
- add usage count of linked projects (`allUsingProjectsCount`)
closes sw360/sw360portal#805

dev(components): hide inaccessible projects in component summary
